/**
 * CPM Schedule Templates — Professional construction schedule templates
 * with full WBS hierarchies, activities, logic ties, and activity codes.
 *
 * Each template follows P6/CPM best practices:
 * - Hierarchical WBS structure
 * - Realistic durations based on industry standards ($500K–$4M projects)
 * - Proper FS/SS/FF logic ties with appropriate lags
 * - Activity codes for Phase and Trade categorization
 * - Every activity linked to a WBS node
 */

export type ScheduleTemplate = {
  name: string;
  description: string;
  activities: Array<{
    activityId: string;
    name: string;
    duration: number;
    wbs: string;
    activityType?: "task" | "milestone";
  }>;
  relationships: Array<{
    pred: string;
    succ: string;
    type: "FS" | "SS" | "FF" | "SF";
    lag: number;
  }>;
  wbsNodes: Array<{
    code: string;
    name: string;
    parentCode: string | null;
    sortOrder: number;
    color: string;
    textColor: string;
  }>;
  codeCategories?: Array<{
    name: string;
    values: string[];
  }>;
};

// ═══════════════════════════════════════════════════════════════════════════════
// COMMERCIAL TENANT IMPROVEMENT — $500K–$2M Office/Retail Buildout
// 8–14 week schedule, 55+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const commercialTiTemplate: ScheduleTemplate = {
  name: "Commercial Tenant Improvement",
  description: "Office/retail TI buildout ($500K–$2M) — demo through punch list with full MEP coordination, ADA compliance, and phased inspections",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "2.0", name: "Demolition & Abatement", parentCode: null, sortOrder: 20, color: "#ef4444", textColor: "#ffffff" },
    { code: "3.0", name: "Structural & Framing", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "4.0", name: "MEP Rough-In", parentCode: null, sortOrder: 40, color: "#3b82f6", textColor: "#ffffff" },
    { code: "4.1", name: "Electrical", parentCode: "4.0", sortOrder: 41, color: "#60a5fa", textColor: "#000000" },
    { code: "4.2", name: "Plumbing", parentCode: "4.0", sortOrder: 42, color: "#93c5fd", textColor: "#000000" },
    { code: "4.3", name: "HVAC", parentCode: "4.0", sortOrder: 43, color: "#bfdbfe", textColor: "#000000" },
    { code: "4.4", name: "Fire Protection", parentCode: "4.0", sortOrder: 44, color: "#dbeafe", textColor: "#000000" },
    { code: "5.0", name: "Inspections & Concealment", parentCode: null, sortOrder: 50, color: "#f97316", textColor: "#ffffff" },
    { code: "6.0", name: "Interior Finishes", parentCode: null, sortOrder: 60, color: "#10b981", textColor: "#ffffff" },
    { code: "6.1", name: "Drywall & Ceilings", parentCode: "6.0", sortOrder: 61, color: "#34d399", textColor: "#000000" },
    { code: "6.2", name: "Flooring & Tile", parentCode: "6.0", sortOrder: 62, color: "#6ee7b7", textColor: "#000000" },
    { code: "6.3", name: "Paint & Wall Coverings", parentCode: "6.0", sortOrder: 63, color: "#a7f3d0", textColor: "#000000" },
    { code: "6.4", name: "Millwork & Specialties", parentCode: "6.0", sortOrder: 64, color: "#d1fae5", textColor: "#000000" },
    { code: "7.0", name: "MEP Trim & Startup", parentCode: null, sortOrder: 70, color: "#06b6d4", textColor: "#ffffff" },
    { code: "8.0", name: "Closeout", parentCode: null, sortOrder: 80, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Construction
    { activityId: "TI1010", name: "Pre-Construction Meeting", duration: 1, wbs: "1.0" },
    { activityId: "TI1020", name: "Submit Building Permit Application", duration: 2, wbs: "1.0" },
    { activityId: "TI1030", name: "Building Permit Review & Approval", duration: 15, wbs: "1.0" },
    { activityId: "TI1040", name: "Submit MEP Shop Drawings", duration: 7, wbs: "1.0" },
    { activityId: "TI1050", name: "MEP Shop Drawing Review", duration: 10, wbs: "1.0" },
    { activityId: "TI1060", name: "Mobilization & Site Protection", duration: 2, wbs: "1.0" },
    { activityId: "TI1070", name: "Order Long-Lead Equipment (HVAC, Switchgear)", duration: 3, wbs: "1.0" },
    { activityId: "TI1080", name: "Long-Lead Equipment Delivery", duration: 21, wbs: "1.0" },
    // 2.0 Demolition
    { activityId: "TI2010", name: "Hazmat Survey & Abatement (if req'd)", duration: 3, wbs: "2.0" },
    { activityId: "TI2020", name: "Selective Demolition — Walls & Ceilings", duration: 5, wbs: "2.0" },
    { activityId: "TI2030", name: "Selective Demolition — MEP Systems", duration: 3, wbs: "2.0" },
    { activityId: "TI2040", name: "Selective Demolition — Flooring", duration: 3, wbs: "2.0" },
    { activityId: "TI2050", name: "Debris Removal & Floor Prep", duration: 2, wbs: "2.0" },
    // 3.0 Structural & Framing
    { activityId: "TI3010", name: "Layout & Snap Lines", duration: 2, wbs: "3.0" },
    { activityId: "TI3020", name: "Structural Modifications (Beams/Headers)", duration: 5, wbs: "3.0" },
    { activityId: "TI3030", name: "Metal Stud Framing — Perimeter Walls", duration: 5, wbs: "3.0" },
    { activityId: "TI3040", name: "Metal Stud Framing — Interior Partitions", duration: 7, wbs: "3.0" },
    { activityId: "TI3050", name: "Door Frame & Hardware Rough-In", duration: 3, wbs: "3.0" },
    { activityId: "TI3060", name: "Blocking & Backing for Millwork/TV/Accessories", duration: 2, wbs: "3.0" },
    // 4.0 MEP Rough-In
    { activityId: "TI4010", name: "Electrical Rough-In — Branch Circuits", duration: 8, wbs: "4.1" },
    { activityId: "TI4020", name: "Electrical Rough-In — Low Voltage & Data", duration: 5, wbs: "4.1" },
    { activityId: "TI4030", name: "Electrical — Panel Upgrades & Feeders", duration: 4, wbs: "4.1" },
    { activityId: "TI4040", name: "Plumbing Rough-In — Waste & Vent", duration: 5, wbs: "4.2" },
    { activityId: "TI4050", name: "Plumbing Rough-In — Water Supply", duration: 4, wbs: "4.2" },
    { activityId: "TI4060", name: "HVAC Ductwork Modifications", duration: 7, wbs: "4.3" },
    { activityId: "TI4070", name: "HVAC — New VAV Boxes & Controls", duration: 4, wbs: "4.3" },
    { activityId: "TI4080", name: "Fire Sprinkler Relocation & New Heads", duration: 5, wbs: "4.4" },
    { activityId: "TI4090", name: "Fire Alarm Modifications", duration: 3, wbs: "4.4" },
    // 5.0 Inspections
    { activityId: "TI5010", name: "MEP Rough-In Inspection", duration: 2, wbs: "5.0" },
    { activityId: "TI5020", name: "Framing Inspection", duration: 1, wbs: "5.0" },
    { activityId: "TI5030", name: "Insulation Installation", duration: 4, wbs: "5.0" },
    { activityId: "TI5040", name: "Insulation Inspection", duration: 1, wbs: "5.0" },
    // 6.0 Interior Finishes
    { activityId: "TI6010", name: "Drywall — Hang", duration: 6, wbs: "6.1" },
    { activityId: "TI6020", name: "Drywall — Tape & Finish (Level 4/5)", duration: 5, wbs: "6.1" },
    { activityId: "TI6030", name: "Ceiling Grid Layout & Install", duration: 5, wbs: "6.1" },
    { activityId: "TI6040", name: "Ceiling Tile Installation", duration: 3, wbs: "6.1" },
    { activityId: "TI6050", name: "Prime Coat", duration: 3, wbs: "6.3" },
    { activityId: "TI6060", name: "Finish Paint — 2 Coats", duration: 5, wbs: "6.3" },
    { activityId: "TI6070", name: "Accent Walls & Wall Coverings", duration: 3, wbs: "6.3" },
    { activityId: "TI6080", name: "Tile — Restrooms & Break Room", duration: 5, wbs: "6.2" },
    { activityId: "TI6090", name: "Carpet Tile Installation", duration: 4, wbs: "6.2" },
    { activityId: "TI6100", name: "LVP/LVT Installation — Common Areas", duration: 3, wbs: "6.2" },
    { activityId: "TI6110", name: "Base & Transition Strips", duration: 2, wbs: "6.2" },
    { activityId: "TI6120", name: "Millwork & Casework Installation", duration: 5, wbs: "6.4" },
    { activityId: "TI6130", name: "Countertops — Fabrication & Install", duration: 4, wbs: "6.4" },
    { activityId: "TI6140", name: "Glass & Glazing — Interior Partitions", duration: 4, wbs: "6.4" },
    { activityId: "TI6150", name: "Signage & Wayfinding", duration: 2, wbs: "6.4" },
    // 7.0 MEP Trim
    { activityId: "TI7010", name: "Electrical Trim — Devices & Covers", duration: 3, wbs: "7.0" },
    { activityId: "TI7020", name: "Electrical — Light Fixtures", duration: 3, wbs: "7.0" },
    { activityId: "TI7030", name: "Low Voltage Trim — Data/AV", duration: 3, wbs: "7.0" },
    { activityId: "TI7040", name: "Plumbing Trim — Fixtures & Faucets", duration: 3, wbs: "7.0" },
    { activityId: "TI7050", name: "HVAC — Diffusers, Grilles & Controls", duration: 2, wbs: "7.0" },
    { activityId: "TI7060", name: "HVAC Test & Balance (TAB)", duration: 3, wbs: "7.0" },
    { activityId: "TI7070", name: "Fire Alarm Testing & Certification", duration: 2, wbs: "7.0" },
    // 8.0 Closeout
    { activityId: "TI8010", name: "Final Clean", duration: 2, wbs: "8.0" },
    { activityId: "TI8020", name: "Punch List Walk", duration: 3, wbs: "8.0" },
    { activityId: "TI8030", name: "Punch List Corrections", duration: 5, wbs: "8.0" },
    { activityId: "TI8040", name: "Final Inspection & Certificate of Occupancy", duration: 3, wbs: "8.0" },
    { activityId: "TI8050", name: "Owner Training & Turnover", duration: 1, wbs: "8.0" },
    { activityId: "TI8060", name: "Substantial Completion", duration: 0, wbs: "8.0", activityType: "milestone" },
  ],
  relationships: [
    { pred: "TI1010", succ: "TI1020", type: "FS", lag: 0 },
    { pred: "TI1020", succ: "TI1030", type: "FS", lag: 0 },
    { pred: "TI1010", succ: "TI1040", type: "FS", lag: 0 },
    { pred: "TI1040", succ: "TI1050", type: "FS", lag: 0 },
    { pred: "TI1010", succ: "TI1070", type: "FS", lag: 0 },
    { pred: "TI1070", succ: "TI1080", type: "FS", lag: 0 },
    { pred: "TI1030", succ: "TI1060", type: "FS", lag: 0 },
    { pred: "TI1060", succ: "TI2010", type: "FS", lag: 0 },
    { pred: "TI2010", succ: "TI2020", type: "FS", lag: 0 },
    { pred: "TI2020", succ: "TI2030", type: "SS", lag: 2 },
    { pred: "TI2020", succ: "TI2040", type: "SS", lag: 3 },
    { pred: "TI2030", succ: "TI2050", type: "FS", lag: 0 },
    { pred: "TI2040", succ: "TI2050", type: "FS", lag: 0 },
    { pred: "TI2050", succ: "TI3010", type: "FS", lag: 0 },
    { pred: "TI3010", succ: "TI3020", type: "FS", lag: 0 },
    { pred: "TI3020", succ: "TI3030", type: "FS", lag: 0 },
    { pred: "TI3030", succ: "TI3040", type: "SS", lag: 2 },
    { pred: "TI3040", succ: "TI3050", type: "SS", lag: 3 },
    { pred: "TI3040", succ: "TI3060", type: "SS", lag: 3 },
    { pred: "TI3050", succ: "TI4010", type: "FS", lag: 0 },
    { pred: "TI3060", succ: "TI4010", type: "FS", lag: 0 },
    { pred: "TI1050", succ: "TI4010", type: "FS", lag: 0 },
    { pred: "TI4010", succ: "TI4020", type: "SS", lag: 3 },
    { pred: "TI4010", succ: "TI4030", type: "SS", lag: 2 },
    { pred: "TI3050", succ: "TI4040", type: "FS", lag: 0 },
    { pred: "TI4040", succ: "TI4050", type: "SS", lag: 2 },
    { pred: "TI1080", succ: "TI4060", type: "FS", lag: 0 },
    { pred: "TI3040", succ: "TI4060", type: "FS", lag: 0 },
    { pred: "TI4060", succ: "TI4070", type: "SS", lag: 3 },
    { pred: "TI3040", succ: "TI4080", type: "FS", lag: 0 },
    { pred: "TI4080", succ: "TI4090", type: "SS", lag: 2 },
    { pred: "TI4010", succ: "TI5010", type: "FS", lag: 0 },
    { pred: "TI4040", succ: "TI5010", type: "FS", lag: 0 },
    { pred: "TI4060", succ: "TI5010", type: "FS", lag: 0 },
    { pred: "TI4080", succ: "TI5010", type: "FS", lag: 0 },
    { pred: "TI3040", succ: "TI5020", type: "FS", lag: 0 },
    { pred: "TI5010", succ: "TI5030", type: "FS", lag: 0 },
    { pred: "TI5020", succ: "TI5030", type: "FS", lag: 0 },
    { pred: "TI5030", succ: "TI5040", type: "FS", lag: 0 },
    { pred: "TI5040", succ: "TI6010", type: "FS", lag: 0 },
    { pred: "TI6010", succ: "TI6020", type: "FS", lag: 0 },
    { pred: "TI6020", succ: "TI6030", type: "FS", lag: 0 },
    { pred: "TI6020", succ: "TI6050", type: "FS", lag: 0 },
    { pred: "TI6050", succ: "TI6060", type: "FS", lag: 0 },
    { pred: "TI6060", succ: "TI6070", type: "FS", lag: 0 },
    { pred: "TI6060", succ: "TI6080", type: "SS", lag: 0 },
    { pred: "TI6070", succ: "TI6090", type: "FS", lag: 0 },
    { pred: "TI6080", succ: "TI6090", type: "FS", lag: 0 },
    { pred: "TI6090", succ: "TI6100", type: "FS", lag: 0 },
    { pred: "TI6100", succ: "TI6110", type: "FS", lag: 0 },
    { pred: "TI6060", succ: "TI6120", type: "FS", lag: 0 },
    { pred: "TI6120", succ: "TI6130", type: "FS", lag: 0 },
    { pred: "TI6030", succ: "TI6140", type: "FS", lag: 0 },
    { pred: "TI6060", succ: "TI6150", type: "FS", lag: 0 },
    { pred: "TI6030", succ: "TI6040", type: "FS", lag: 0 },
    { pred: "TI6110", succ: "TI7010", type: "FS", lag: 0 },
    { pred: "TI6130", succ: "TI7010", type: "FS", lag: 0 },
    { pred: "TI7010", succ: "TI7020", type: "SS", lag: 1 },
    { pred: "TI7010", succ: "TI7030", type: "SS", lag: 1 },
    { pred: "TI7010", succ: "TI7040", type: "SS", lag: 1 },
    { pred: "TI7020", succ: "TI7050", type: "FS", lag: 0 },
    { pred: "TI7050", succ: "TI7060", type: "FS", lag: 0 },
    { pred: "TI4090", succ: "TI7070", type: "FS", lag: 0 },
    { pred: "TI7060", succ: "TI7070", type: "FS", lag: 0 },
    { pred: "TI7070", succ: "TI8010", type: "FS", lag: 0 },
    { pred: "TI6150", succ: "TI8010", type: "FS", lag: 0 },
    { pred: "TI6040", succ: "TI8010", type: "FS", lag: 0 },
    { pred: "TI8010", succ: "TI8020", type: "FS", lag: 0 },
    { pred: "TI8020", succ: "TI8030", type: "FS", lag: 0 },
    { pred: "TI8030", succ: "TI8040", type: "FS", lag: 0 },
    { pred: "TI8040", succ: "TI8050", type: "FS", lag: 0 },
    { pred: "TI8050", succ: "TI8060", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Demo", "Framing", "MEP Rough", "Inspections", "Drywall", "Finishes", "MEP Trim", "Closeout"] },
    { name: "Trade", values: ["General", "Electrical", "Plumbing", "HVAC", "Fire Protection", "Drywall", "Paint", "Flooring", "Tile", "Millwork", "Glass"] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// RENOVATION / REMODEL — $500K–$2M Existing Structure Renovation
// 10–16 week schedule, 55+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const renovationTemplate: ScheduleTemplate = {
  name: "Renovation / Remodel",
  description: "Existing structure renovation ($500K–$2M) — hazmat abatement, selective demo, structural mods, full MEP rework, and phased finishes",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction & Permits", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "2.0", name: "Abatement & Demolition", parentCode: null, sortOrder: 20, color: "#ef4444", textColor: "#ffffff" },
    { code: "2.1", name: "Hazmat Abatement", parentCode: "2.0", sortOrder: 21, color: "#f87171", textColor: "#000000" },
    { code: "2.2", name: "Selective Demolition", parentCode: "2.0", sortOrder: 22, color: "#fca5a5", textColor: "#000000" },
    { code: "3.0", name: "Structural & Framing", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "4.0", name: "MEP Rough-In", parentCode: null, sortOrder: 40, color: "#3b82f6", textColor: "#ffffff" },
    { code: "4.1", name: "Electrical", parentCode: "4.0", sortOrder: 41, color: "#60a5fa", textColor: "#000000" },
    { code: "4.2", name: "Plumbing", parentCode: "4.0", sortOrder: 42, color: "#93c5fd", textColor: "#000000" },
    { code: "4.3", name: "HVAC", parentCode: "4.0", sortOrder: 43, color: "#bfdbfe", textColor: "#000000" },
    { code: "5.0", name: "Enclosure & Weatherproofing", parentCode: null, sortOrder: 50, color: "#06b6d4", textColor: "#ffffff" },
    { code: "6.0", name: "Interior Finishes", parentCode: null, sortOrder: 60, color: "#10b981", textColor: "#ffffff" },
    { code: "6.1", name: "Drywall & Plaster", parentCode: "6.0", sortOrder: 61, color: "#34d399", textColor: "#000000" },
    { code: "6.2", name: "Tile & Stone", parentCode: "6.0", sortOrder: 62, color: "#6ee7b7", textColor: "#000000" },
    { code: "6.3", name: "Paint & Finishes", parentCode: "6.0", sortOrder: 63, color: "#a7f3d0", textColor: "#000000" },
    { code: "6.4", name: "Flooring", parentCode: "6.0", sortOrder: 64, color: "#d1fae5", textColor: "#000000" },
    { code: "6.5", name: "Cabinets & Millwork", parentCode: "6.0", sortOrder: 65, color: "#ecfdf5", textColor: "#000000" },
    { code: "7.0", name: "MEP Trim & Startup", parentCode: null, sortOrder: 70, color: "#14b8a6", textColor: "#ffffff" },
    { code: "8.0", name: "Closeout", parentCode: null, sortOrder: 80, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Construction
    { activityId: "RN1010", name: "Pre-Construction Walkthrough & Survey", duration: 2, wbs: "1.0" },
    { activityId: "RN1020", name: "Hazmat Testing & Report", duration: 5, wbs: "1.0" },
    { activityId: "RN1030", name: "Submit Building Permit", duration: 2, wbs: "1.0" },
    { activityId: "RN1040", name: "Permit Review & Approval", duration: 14, wbs: "1.0" },
    { activityId: "RN1050", name: "Submit MEP Shop Drawings", duration: 7, wbs: "1.0" },
    { activityId: "RN1060", name: "Shop Drawing Review", duration: 10, wbs: "1.0" },
    { activityId: "RN1070", name: "Mobilization & Protection of Existing", duration: 3, wbs: "1.0" },
    // 2.0 Abatement & Demo
    { activityId: "RN2010", name: "Lead Paint Abatement", duration: 5, wbs: "2.1" },
    { activityId: "RN2020", name: "Asbestos Abatement (if applicable)", duration: 5, wbs: "2.1" },
    { activityId: "RN2030", name: "Clearance Testing", duration: 2, wbs: "2.1" },
    { activityId: "RN2040", name: "Selective Demo — Interior Walls", duration: 5, wbs: "2.2" },
    { activityId: "RN2050", name: "Selective Demo — Ceilings & Soffits", duration: 3, wbs: "2.2" },
    { activityId: "RN2060", name: "Selective Demo — Flooring", duration: 3, wbs: "2.2" },
    { activityId: "RN2070", name: "Selective Demo — MEP Systems", duration: 4, wbs: "2.2" },
    { activityId: "RN2080", name: "Debris Removal & Dumpster Haul", duration: 2, wbs: "2.2" },
    // 3.0 Structural
    { activityId: "RN3010", name: "Structural Assessment & Layout", duration: 3, wbs: "3.0" },
    { activityId: "RN3020", name: "Structural Steel — Beams & Headers", duration: 5, wbs: "3.0" },
    { activityId: "RN3030", name: "Foundation Repair / Underpinning", duration: 7, wbs: "3.0" },
    { activityId: "RN3040", name: "New Wall Framing — Metal Stud", duration: 6, wbs: "3.0" },
    { activityId: "RN3050", name: "Subfloor Repair & Leveling", duration: 4, wbs: "3.0" },
    { activityId: "RN3060", name: "Blocking & Backing", duration: 2, wbs: "3.0" },
    // 4.0 MEP Rough-In
    { activityId: "RN4010", name: "Electrical Panel Upgrade", duration: 4, wbs: "4.1" },
    { activityId: "RN4020", name: "Electrical Rough-In — New Circuits", duration: 7, wbs: "4.1" },
    { activityId: "RN4030", name: "Low Voltage — Data/Phone/Security", duration: 4, wbs: "4.1" },
    { activityId: "RN4040", name: "Plumbing — Re-route Waste & Vent", duration: 5, wbs: "4.2" },
    { activityId: "RN4050", name: "Plumbing — New Water Supply Lines", duration: 4, wbs: "4.2" },
    { activityId: "RN4060", name: "HVAC — Ductwork Modifications", duration: 6, wbs: "4.3" },
    { activityId: "RN4070", name: "HVAC — New Equipment Installation", duration: 4, wbs: "4.3" },
    { activityId: "RN4080", name: "MEP Rough-In Inspection", duration: 2, wbs: "4.0" },
    // 5.0 Enclosure
    { activityId: "RN5010", name: "Window Replacement", duration: 5, wbs: "5.0" },
    { activityId: "RN5020", name: "Exterior Door Replacement", duration: 3, wbs: "5.0" },
    { activityId: "RN5030", name: "Roofing Repairs / Replacement", duration: 5, wbs: "5.0" },
    { activityId: "RN5040", name: "Exterior Siding / Stucco Repair", duration: 5, wbs: "5.0" },
    { activityId: "RN5050", name: "Waterproofing & Flashing", duration: 3, wbs: "5.0" },
    // 6.0 Interior Finishes
    { activityId: "RN6010", name: "Insulation — Walls & Ceilings", duration: 4, wbs: "6.1" },
    { activityId: "RN6020", name: "Insulation Inspection", duration: 1, wbs: "6.1" },
    { activityId: "RN6030", name: "Drywall — Hang", duration: 6, wbs: "6.1" },
    { activityId: "RN6040", name: "Drywall — Tape & Finish", duration: 5, wbs: "6.1" },
    { activityId: "RN6050", name: "Plaster Repair & Skim Coat", duration: 4, wbs: "6.1" },
    { activityId: "RN6060", name: "Tile — Bathroom Floors & Walls", duration: 5, wbs: "6.2" },
    { activityId: "RN6070", name: "Tile — Kitchen Backsplash", duration: 3, wbs: "6.2" },
    { activityId: "RN6080", name: "Prime & Paint — Walls", duration: 5, wbs: "6.3" },
    { activityId: "RN6090", name: "Paint — Trim & Doors", duration: 4, wbs: "6.3" },
    { activityId: "RN6100", name: "Hardwood Floor Refinish / Install", duration: 5, wbs: "6.4" },
    { activityId: "RN6110", name: "Carpet Installation", duration: 3, wbs: "6.4" },
    { activityId: "RN6120", name: "LVP/LVT Installation", duration: 3, wbs: "6.4" },
    { activityId: "RN6130", name: "Base & Transition Strips", duration: 2, wbs: "6.4" },
    { activityId: "RN6140", name: "Cabinet Installation — Kitchen", duration: 4, wbs: "6.5" },
    { activityId: "RN6150", name: "Cabinet Installation — Bathrooms", duration: 3, wbs: "6.5" },
    { activityId: "RN6160", name: "Countertop Fabrication & Install", duration: 5, wbs: "6.5" },
    { activityId: "RN6170", name: "Interior Doors & Hardware", duration: 3, wbs: "6.5" },
    // 7.0 MEP Trim
    { activityId: "RN7010", name: "Electrical Trim — Devices & Covers", duration: 3, wbs: "7.0" },
    { activityId: "RN7020", name: "Light Fixture Installation", duration: 3, wbs: "7.0" },
    { activityId: "RN7030", name: "Plumbing Trim — Fixtures & Faucets", duration: 3, wbs: "7.0" },
    { activityId: "RN7040", name: "HVAC Trim — Registers & Thermostats", duration: 2, wbs: "7.0" },
    { activityId: "RN7050", name: "Appliance Installation", duration: 2, wbs: "7.0" },
    { activityId: "RN7060", name: "Hardware & Accessories", duration: 2, wbs: "7.0" },
    // 8.0 Closeout
    { activityId: "RN8010", name: "Final Clean", duration: 2, wbs: "8.0" },
    { activityId: "RN8020", name: "Punch List Walk", duration: 2, wbs: "8.0" },
    { activityId: "RN8030", name: "Punch List Corrections", duration: 5, wbs: "8.0" },
    { activityId: "RN8040", name: "Final Inspection", duration: 2, wbs: "8.0" },
    { activityId: "RN8050", name: "Substantial Completion", duration: 0, wbs: "8.0", activityType: "milestone" },
  ],
  relationships: [
    { pred: "RN1010", succ: "RN1020", type: "FS", lag: 0 },
    { pred: "RN1010", succ: "RN1030", type: "FS", lag: 0 },
    { pred: "RN1030", succ: "RN1040", type: "FS", lag: 0 },
    { pred: "RN1010", succ: "RN1050", type: "FS", lag: 0 },
    { pred: "RN1050", succ: "RN1060", type: "FS", lag: 0 },
    { pred: "RN1040", succ: "RN1070", type: "FS", lag: 0 },
    { pred: "RN1020", succ: "RN2010", type: "FS", lag: 0 },
    { pred: "RN1070", succ: "RN2010", type: "FS", lag: 0 },
    { pred: "RN2010", succ: "RN2020", type: "SS", lag: 0 },
    { pred: "RN2020", succ: "RN2030", type: "FS", lag: 0 },
    { pred: "RN2030", succ: "RN2040", type: "FS", lag: 0 },
    { pred: "RN2040", succ: "RN2050", type: "SS", lag: 2 },
    { pred: "RN2040", succ: "RN2060", type: "SS", lag: 2 },
    { pred: "RN2050", succ: "RN2070", type: "FS", lag: 0 },
    { pred: "RN2060", succ: "RN2070", type: "FS", lag: 0 },
    { pred: "RN2070", succ: "RN2080", type: "FS", lag: 0 },
    { pred: "RN2080", succ: "RN3010", type: "FS", lag: 0 },
    { pred: "RN3010", succ: "RN3020", type: "FS", lag: 0 },
    { pred: "RN3010", succ: "RN3030", type: "FS", lag: 0 },
    { pred: "RN3020", succ: "RN3040", type: "FS", lag: 0 },
    { pred: "RN3030", succ: "RN3040", type: "FS", lag: 0 },
    { pred: "RN3040", succ: "RN3050", type: "SS", lag: 3 },
    { pred: "RN3040", succ: "RN3060", type: "SS", lag: 3 },
    { pred: "RN3060", succ: "RN4010", type: "FS", lag: 0 },
    { pred: "RN1060", succ: "RN4010", type: "FS", lag: 0 },
    { pred: "RN4010", succ: "RN4020", type: "FS", lag: 0 },
    { pred: "RN4020", succ: "RN4030", type: "SS", lag: 3 },
    { pred: "RN3060", succ: "RN4040", type: "FS", lag: 0 },
    { pred: "RN4040", succ: "RN4050", type: "SS", lag: 2 },
    { pred: "RN3060", succ: "RN4060", type: "FS", lag: 0 },
    { pred: "RN4060", succ: "RN4070", type: "SS", lag: 3 },
    { pred: "RN4020", succ: "RN4080", type: "FS", lag: 0 },
    { pred: "RN4040", succ: "RN4080", type: "FS", lag: 0 },
    { pred: "RN4060", succ: "RN4080", type: "FS", lag: 0 },
    { pred: "RN3040", succ: "RN5010", type: "FS", lag: 0 },
    { pred: "RN5010", succ: "RN5020", type: "SS", lag: 2 },
    { pred: "RN3040", succ: "RN5030", type: "FS", lag: 0 },
    { pred: "RN5030", succ: "RN5040", type: "FS", lag: 0 },
    { pred: "RN5040", succ: "RN5050", type: "FS", lag: 0 },
    { pred: "RN4080", succ: "RN6010", type: "FS", lag: 0 },
    { pred: "RN6010", succ: "RN6020", type: "FS", lag: 0 },
    { pred: "RN6020", succ: "RN6030", type: "FS", lag: 0 },
    { pred: "RN6030", succ: "RN6040", type: "FS", lag: 0 },
    { pred: "RN6040", succ: "RN6050", type: "FS", lag: 0 },
    { pred: "RN6050", succ: "RN6080", type: "FS", lag: 0 },
    { pred: "RN6050", succ: "RN6060", type: "FS", lag: 0 },
    { pred: "RN6060", succ: "RN6070", type: "FS", lag: 0 },
    { pred: "RN6080", succ: "RN6090", type: "SS", lag: 2 },
    { pred: "RN6090", succ: "RN6100", type: "FS", lag: 0 },
    { pred: "RN6100", succ: "RN6110", type: "FS", lag: 0 },
    { pred: "RN6110", succ: "RN6120", type: "FS", lag: 0 },
    { pred: "RN6120", succ: "RN6130", type: "FS", lag: 0 },
    { pred: "RN6050", succ: "RN6140", type: "FS", lag: 0 },
    { pred: "RN6060", succ: "RN6150", type: "FS", lag: 0 },
    { pred: "RN6140", succ: "RN6160", type: "FS", lag: 0 },
    { pred: "RN6150", succ: "RN6160", type: "FS", lag: 0 },
    { pred: "RN6090", succ: "RN6170", type: "FS", lag: 0 },
    { pred: "RN6130", succ: "RN7010", type: "FS", lag: 0 },
    { pred: "RN6160", succ: "RN7010", type: "FS", lag: 0 },
    { pred: "RN7010", succ: "RN7020", type: "SS", lag: 1 },
    { pred: "RN7010", succ: "RN7030", type: "SS", lag: 1 },
    { pred: "RN7030", succ: "RN7040", type: "SS", lag: 1 },
    { pred: "RN7040", succ: "RN7050", type: "FS", lag: 0 },
    { pred: "RN7050", succ: "RN7060", type: "FS", lag: 0 },
    { pred: "RN7060", succ: "RN8010", type: "FS", lag: 0 },
    { pred: "RN5050", succ: "RN8010", type: "FS", lag: 0 },
    { pred: "RN8010", succ: "RN8020", type: "FS", lag: 0 },
    { pred: "RN8020", succ: "RN8030", type: "FS", lag: 0 },
    { pred: "RN8030", succ: "RN8040", type: "FS", lag: 0 },
    { pred: "RN8040", succ: "RN8050", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Abatement", "Demo", "Structural", "MEP Rough", "Enclosure", "Finishes", "MEP Trim", "Closeout"] },
    { name: "Trade", values: ["General", "Abatement", "Structural", "Electrical", "Plumbing", "HVAC", "Drywall", "Tile", "Paint", "Flooring", "Millwork", "Roofing"] },
  ],
};


// ═══════════════════════════════════════════════════════════════════════════════
// HOSPITAL / HEALTHCARE FACILITY — $2M–$4M+ Acute Care or Medical Office
// 18–24 month schedule, 80+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const hospitalTemplate: ScheduleTemplate = {
  name: "Hospital / Healthcare Facility",
  description: "Full-service healthcare facility ($2M–$4M) — sitework through commissioning with MEP-heavy sequencing, infection control, and phased occupancy",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction & Design", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "1.1", name: "Permits & Approvals", parentCode: "1.0", sortOrder: 11, color: "#fbbf24", textColor: "#000000" },
    { code: "1.2", name: "Submittals & Procurement", parentCode: "1.0", sortOrder: 12, color: "#fcd34d", textColor: "#000000" },
    { code: "2.0", name: "Sitework & Utilities", parentCode: null, sortOrder: 20, color: "#84cc16", textColor: "#ffffff" },
    { code: "3.0", name: "Foundations & Structure", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "3.1", name: "Foundations", parentCode: "3.0", sortOrder: 31, color: "#a78bfa", textColor: "#000000" },
    { code: "3.2", name: "Structural Frame", parentCode: "3.0", sortOrder: 32, color: "#c4b5fd", textColor: "#000000" },
    { code: "4.0", name: "Building Enclosure", parentCode: null, sortOrder: 40, color: "#06b6d4", textColor: "#ffffff" },
    { code: "5.0", name: "MEP Rough-In", parentCode: null, sortOrder: 50, color: "#3b82f6", textColor: "#ffffff" },
    { code: "5.1", name: "Electrical & Low Voltage", parentCode: "5.0", sortOrder: 51, color: "#60a5fa", textColor: "#000000" },
    { code: "5.2", name: "Plumbing & Medical Gas", parentCode: "5.0", sortOrder: 52, color: "#93c5fd", textColor: "#000000" },
    { code: "5.3", name: "HVAC & Air Handling", parentCode: "5.0", sortOrder: 53, color: "#bfdbfe", textColor: "#000000" },
    { code: "5.4", name: "Fire Protection", parentCode: "5.0", sortOrder: 54, color: "#dbeafe", textColor: "#000000" },
    { code: "6.0", name: "Interior Finishes", parentCode: null, sortOrder: 60, color: "#10b981", textColor: "#ffffff" },
    { code: "6.1", name: "Drywall & Ceilings", parentCode: "6.0", sortOrder: 61, color: "#34d399", textColor: "#000000" },
    { code: "6.2", name: "Flooring & Wall Protection", parentCode: "6.0", sortOrder: 62, color: "#6ee7b7", textColor: "#000000" },
    { code: "6.3", name: "Casework & Specialties", parentCode: "6.0", sortOrder: 63, color: "#a7f3d0", textColor: "#000000" },
    { code: "7.0", name: "MEP Trim & Equipment", parentCode: null, sortOrder: 70, color: "#14b8a6", textColor: "#ffffff" },
    { code: "8.0", name: "Commissioning & Closeout", parentCode: null, sortOrder: 80, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Construction
    { activityId: "HP1010", name: "Owner/Architect/Contractor Kickoff", duration: 1, wbs: "1.0" },
    { activityId: "HP1020", name: "Submit Building Permit Package", duration: 5, wbs: "1.1" },
    { activityId: "HP1030", name: "Building Permit Review", duration: 21, wbs: "1.1" },
    { activityId: "HP1040", name: "OSHPD / State Health Dept Review (if req'd)", duration: 30, wbs: "1.1" },
    { activityId: "HP1050", name: "Submit Structural Steel Shop Drawings", duration: 10, wbs: "1.2" },
    { activityId: "HP1060", name: "Structural Steel Review & Approval", duration: 14, wbs: "1.2" },
    { activityId: "HP1070", name: "Submit MEP Coordination Drawings", duration: 10, wbs: "1.2" },
    { activityId: "HP1080", name: "MEP Coordination Review", duration: 14, wbs: "1.2" },
    { activityId: "HP1090", name: "Order Medical Gas Equipment", duration: 3, wbs: "1.2" },
    { activityId: "HP1100", name: "Medical Gas Equipment Lead Time", duration: 42, wbs: "1.2" },
    { activityId: "HP1110", name: "Order AHU / RTU Equipment", duration: 3, wbs: "1.2" },
    { activityId: "HP1120", name: "AHU / RTU Lead Time & Delivery", duration: 56, wbs: "1.2" },
    { activityId: "HP1130", name: "Order Generator & Transfer Switch", duration: 3, wbs: "1.2" },
    { activityId: "HP1140", name: "Generator Lead Time & Delivery", duration: 49, wbs: "1.2" },
    // 2.0 Sitework
    { activityId: "HP2010", name: "Mobilization & Erosion Control", duration: 3, wbs: "2.0" },
    { activityId: "HP2020", name: "Site Clearing & Grading", duration: 7, wbs: "2.0" },
    { activityId: "HP2030", name: "Underground Utilities — Storm", duration: 10, wbs: "2.0" },
    { activityId: "HP2040", name: "Underground Utilities — Sanitary", duration: 7, wbs: "2.0" },
    { activityId: "HP2050", name: "Underground Utilities — Water & Fire Main", duration: 7, wbs: "2.0" },
    { activityId: "HP2060", name: "Underground Electrical & Telecom Ductbank", duration: 5, wbs: "2.0" },
    // 3.0 Foundations & Structure
    { activityId: "HP3010", name: "Excavation — Building Pad", duration: 5, wbs: "3.1" },
    { activityId: "HP3020", name: "Foundation Footings", duration: 10, wbs: "3.1" },
    { activityId: "HP3030", name: "Foundation Walls & Grade Beams", duration: 10, wbs: "3.1" },
    { activityId: "HP3040", name: "Underslab Plumbing & Medical Gas", duration: 7, wbs: "3.1" },
    { activityId: "HP3050", name: "Slab on Grade — Pour & Cure", duration: 7, wbs: "3.1" },
    { activityId: "HP3060", name: "Structural Steel Erection — Phase 1", duration: 15, wbs: "3.2" },
    { activityId: "HP3070", name: "Structural Steel Erection — Phase 2", duration: 12, wbs: "3.2" },
    { activityId: "HP3080", name: "Metal Deck & Shear Studs", duration: 8, wbs: "3.2" },
    { activityId: "HP3090", name: "Elevated Concrete Decks — Pour & Cure", duration: 10, wbs: "3.2" },
    { activityId: "HP3100", name: "CMU Walls & Elevator Shafts", duration: 10, wbs: "3.2" },
    // 4.0 Building Enclosure
    { activityId: "HP4010", name: "Exterior Wall Framing & Sheathing", duration: 12, wbs: "4.0" },
    { activityId: "HP4020", name: "Air & Moisture Barrier", duration: 7, wbs: "4.0" },
    { activityId: "HP4030", name: "Window & Curtain Wall Installation", duration: 10, wbs: "4.0" },
    { activityId: "HP4040", name: "Exterior Insulation & Metal Panel", duration: 12, wbs: "4.0" },
    { activityId: "HP4050", name: "Roofing — TPO/EPDM Membrane", duration: 10, wbs: "4.0" },
    { activityId: "HP4060", name: "Roof Penetrations & Flashing", duration: 5, wbs: "4.0" },
    // 5.0 MEP Rough-In
    { activityId: "HP5010", name: "Electrical — Main Switchgear & Distribution", duration: 7, wbs: "5.1" },
    { activityId: "HP5020", name: "Electrical — Branch Circuit Rough-In", duration: 15, wbs: "5.1" },
    { activityId: "HP5030", name: "Electrical — Emergency Power & Generator", duration: 7, wbs: "5.1" },
    { activityId: "HP5040", name: "Low Voltage — Nurse Call, Data, Security", duration: 10, wbs: "5.1" },
    { activityId: "HP5050", name: "Plumbing — Domestic Water Risers", duration: 7, wbs: "5.2" },
    { activityId: "HP5060", name: "Plumbing — Waste & Vent Risers", duration: 7, wbs: "5.2" },
    { activityId: "HP5070", name: "Medical Gas Piping — O2, Vacuum, Air", duration: 10, wbs: "5.2" },
    { activityId: "HP5080", name: "Medical Gas Testing & Certification", duration: 5, wbs: "5.2" },
    { activityId: "HP5090", name: "HVAC — Main Ductwork Runs", duration: 15, wbs: "5.3" },
    { activityId: "HP5100", name: "HVAC — AHU / RTU Installation", duration: 7, wbs: "5.3" },
    { activityId: "HP5110", name: "HVAC — VAV Boxes & Controls", duration: 7, wbs: "5.3" },
    { activityId: "HP5120", name: "HVAC — Chilled & Hot Water Piping", duration: 10, wbs: "5.3" },
    { activityId: "HP5130", name: "Fire Sprinkler — Main & Branch Lines", duration: 10, wbs: "5.4" },
    { activityId: "HP5140", name: "Fire Alarm — Devices & Wiring", duration: 7, wbs: "5.4" },
    { activityId: "HP5150", name: "MEP Rough-In Inspections (phased)", duration: 5, wbs: "5.0" },
    // 6.0 Interior Finishes
    { activityId: "HP6010", name: "Interior Metal Stud Framing", duration: 15, wbs: "6.1" },
    { activityId: "HP6020", name: "Insulation — Walls & Ceilings", duration: 7, wbs: "6.1" },
    { activityId: "HP6030", name: "Drywall — Hang", duration: 12, wbs: "6.1" },
    { activityId: "HP6040", name: "Drywall — Tape & Finish (Level 5 at OR)", duration: 10, wbs: "6.1" },
    { activityId: "HP6050", name: "Ceiling Grid & Tile (Cleanroom rated)", duration: 8, wbs: "6.1" },
    { activityId: "HP6060", name: "Prime & Paint — Walls & Ceilings", duration: 10, wbs: "6.2" },
    { activityId: "HP6070", name: "Epoxy Flooring — OR & Labs", duration: 7, wbs: "6.2" },
    { activityId: "HP6080", name: "Sheet Vinyl — Patient Rooms & Corridors", duration: 8, wbs: "6.2" },
    { activityId: "HP6090", name: "Carpet Tile — Admin & Offices", duration: 4, wbs: "6.2" },
    { activityId: "HP6100", name: "Wall Protection — Corner Guards & Rails", duration: 5, wbs: "6.2" },
    { activityId: "HP6110", name: "Medical Casework & Headwalls", duration: 10, wbs: "6.3" },
    { activityId: "HP6120", name: "Countertops — Solid Surface", duration: 5, wbs: "6.3" },
    { activityId: "HP6130", name: "Interior Doors & Hardware (Latchsets, Closers)", duration: 7, wbs: "6.3" },
    { activityId: "HP6140", name: "Toilet Accessories & Partitions", duration: 4, wbs: "6.3" },
    // 7.0 MEP Trim & Equipment
    { activityId: "HP7010", name: "Electrical Trim — Devices & Covers", duration: 7, wbs: "7.0" },
    { activityId: "HP7020", name: "Light Fixtures — LED & Surgical", duration: 7, wbs: "7.0" },
    { activityId: "HP7030", name: "Nurse Call System Trim & Test", duration: 5, wbs: "7.0" },
    { activityId: "HP7040", name: "Plumbing Trim — Fixtures & Faucets", duration: 5, wbs: "7.0" },
    { activityId: "HP7050", name: "Medical Gas Outlets & Alarms", duration: 5, wbs: "7.0" },
    { activityId: "HP7060", name: "HVAC — Diffusers, Grilles & Controls", duration: 5, wbs: "7.0" },
    { activityId: "HP7070", name: "HVAC Test & Balance (TAB)", duration: 7, wbs: "7.0" },
    { activityId: "HP7080", name: "Fire Alarm Testing & Certification", duration: 5, wbs: "7.0" },
    { activityId: "HP7090", name: "Elevator Installation & Testing", duration: 15, wbs: "7.0" },
    // 8.0 Commissioning & Closeout
    { activityId: "HP8010", name: "Functional Performance Testing", duration: 10, wbs: "8.0" },
    { activityId: "HP8020", name: "ICRA / Infection Control Verification", duration: 5, wbs: "8.0" },
    { activityId: "HP8030", name: "Owner Equipment Installation (by owner)", duration: 10, wbs: "8.0" },
    { activityId: "HP8040", name: "Final Clean (Hospital-Grade)", duration: 5, wbs: "8.0" },
    { activityId: "HP8050", name: "Punch List Walk", duration: 5, wbs: "8.0" },
    { activityId: "HP8060", name: "Punch List Corrections", duration: 10, wbs: "8.0" },
    { activityId: "HP8070", name: "Final Inspections — Building, Fire, Health", duration: 5, wbs: "8.0" },
    { activityId: "HP8080", name: "Staff Training & Orientation", duration: 5, wbs: "8.0" },
    { activityId: "HP8090", name: "Certificate of Occupancy", duration: 0, wbs: "8.0", activityType: "milestone" },
  ],
  relationships: [
    // Pre-con chain
    { pred: "HP1010", succ: "HP1020", type: "FS", lag: 0 },
    { pred: "HP1020", succ: "HP1030", type: "FS", lag: 0 },
    { pred: "HP1030", succ: "HP1040", type: "SS", lag: 0 },
    { pred: "HP1010", succ: "HP1050", type: "FS", lag: 0 },
    { pred: "HP1050", succ: "HP1060", type: "FS", lag: 0 },
    { pred: "HP1010", succ: "HP1070", type: "FS", lag: 0 },
    { pred: "HP1070", succ: "HP1080", type: "FS", lag: 0 },
    { pred: "HP1010", succ: "HP1090", type: "FS", lag: 0 },
    { pred: "HP1090", succ: "HP1100", type: "FS", lag: 0 },
    { pred: "HP1010", succ: "HP1110", type: "FS", lag: 0 },
    { pred: "HP1110", succ: "HP1120", type: "FS", lag: 0 },
    { pred: "HP1010", succ: "HP1130", type: "FS", lag: 0 },
    { pred: "HP1130", succ: "HP1140", type: "FS", lag: 0 },
    // Sitework
    { pred: "HP1030", succ: "HP2010", type: "FS", lag: 0 },
    { pred: "HP2010", succ: "HP2020", type: "FS", lag: 0 },
    { pred: "HP2020", succ: "HP2030", type: "FS", lag: 0 },
    { pred: "HP2020", succ: "HP2040", type: "SS", lag: 3 },
    { pred: "HP2020", succ: "HP2050", type: "SS", lag: 3 },
    { pred: "HP2020", succ: "HP2060", type: "SS", lag: 5 },
    // Foundations
    { pred: "HP2030", succ: "HP3010", type: "FS", lag: 0 },
    { pred: "HP2040", succ: "HP3010", type: "FS", lag: 0 },
    { pred: "HP3010", succ: "HP3020", type: "FS", lag: 0 },
    { pred: "HP3020", succ: "HP3030", type: "FS", lag: 0 },
    { pred: "HP3030", succ: "HP3040", type: "FS", lag: 0 },
    { pred: "HP3040", succ: "HP3050", type: "FS", lag: 0 },
    // Structure
    { pred: "HP3050", succ: "HP3060", type: "FS", lag: 0 },
    { pred: "HP1060", succ: "HP3060", type: "FS", lag: 0 },
    { pred: "HP3060", succ: "HP3070", type: "FS", lag: 0 },
    { pred: "HP3070", succ: "HP3080", type: "SS", lag: 5 },
    { pred: "HP3080", succ: "HP3090", type: "FS", lag: 0 },
    { pred: "HP3070", succ: "HP3100", type: "SS", lag: 5 },
    // Enclosure
    { pred: "HP3090", succ: "HP4010", type: "FS", lag: 0 },
    { pred: "HP4010", succ: "HP4020", type: "SS", lag: 5 },
    { pred: "HP4020", succ: "HP4030", type: "SS", lag: 3 },
    { pred: "HP4030", succ: "HP4040", type: "SS", lag: 5 },
    { pred: "HP3090", succ: "HP4050", type: "FS", lag: 0 },
    { pred: "HP4050", succ: "HP4060", type: "FS", lag: 0 },
    // MEP Rough-In
    { pred: "HP4010", succ: "HP5010", type: "FS", lag: 0 },
    { pred: "HP1140", succ: "HP5030", type: "FS", lag: 0 },
    { pred: "HP5010", succ: "HP5020", type: "SS", lag: 3 },
    { pred: "HP5010", succ: "HP5030", type: "SS", lag: 3 },
    { pred: "HP5020", succ: "HP5040", type: "SS", lag: 5 },
    { pred: "HP4010", succ: "HP5050", type: "FS", lag: 0 },
    { pred: "HP5050", succ: "HP5060", type: "SS", lag: 3 },
    { pred: "HP1100", succ: "HP5070", type: "FS", lag: 0 },
    { pred: "HP5050", succ: "HP5070", type: "SS", lag: 3 },
    { pred: "HP5070", succ: "HP5080", type: "FS", lag: 0 },
    { pred: "HP1080", succ: "HP5090", type: "FS", lag: 0 },
    { pred: "HP4010", succ: "HP5090", type: "FS", lag: 0 },
    { pred: "HP1120", succ: "HP5100", type: "FS", lag: 0 },
    { pred: "HP5090", succ: "HP5100", type: "SS", lag: 5 },
    { pred: "HP5100", succ: "HP5110", type: "FS", lag: 0 },
    { pred: "HP5090", succ: "HP5120", type: "SS", lag: 5 },
    { pred: "HP4010", succ: "HP5130", type: "FS", lag: 0 },
    { pred: "HP5130", succ: "HP5140", type: "SS", lag: 5 },
    { pred: "HP5020", succ: "HP5150", type: "FS", lag: 0 },
    { pred: "HP5060", succ: "HP5150", type: "FS", lag: 0 },
    { pred: "HP5090", succ: "HP5150", type: "FS", lag: 0 },
    { pred: "HP5130", succ: "HP5150", type: "FS", lag: 0 },
    // Interior Finishes
    { pred: "HP5150", succ: "HP6010", type: "FS", lag: 0 },
    { pred: "HP6010", succ: "HP6020", type: "SS", lag: 5 },
    { pred: "HP6020", succ: "HP6030", type: "FS", lag: 0 },
    { pred: "HP6030", succ: "HP6040", type: "FS", lag: 0 },
    { pred: "HP6040", succ: "HP6050", type: "FS", lag: 0 },
    { pred: "HP6040", succ: "HP6060", type: "FS", lag: 0 },
    { pred: "HP6060", succ: "HP6070", type: "FS", lag: 0 },
    { pred: "HP6060", succ: "HP6080", type: "SS", lag: 3 },
    { pred: "HP6080", succ: "HP6090", type: "FS", lag: 0 },
    { pred: "HP6060", succ: "HP6100", type: "FS", lag: 0 },
    { pred: "HP6040", succ: "HP6110", type: "FS", lag: 0 },
    { pred: "HP6110", succ: "HP6120", type: "FS", lag: 0 },
    { pred: "HP6040", succ: "HP6130", type: "FS", lag: 0 },
    { pred: "HP6060", succ: "HP6140", type: "FS", lag: 0 },
    // MEP Trim
    { pred: "HP6090", succ: "HP7010", type: "FS", lag: 0 },
    { pred: "HP6120", succ: "HP7010", type: "FS", lag: 0 },
    { pred: "HP7010", succ: "HP7020", type: "SS", lag: 2 },
    { pred: "HP7010", succ: "HP7030", type: "SS", lag: 2 },
    { pred: "HP7010", succ: "HP7040", type: "SS", lag: 2 },
    { pred: "HP5080", succ: "HP7050", type: "FS", lag: 0 },
    { pred: "HP7040", succ: "HP7050", type: "SS", lag: 2 },
    { pred: "HP7020", succ: "HP7060", type: "FS", lag: 0 },
    { pred: "HP5110", succ: "HP7060", type: "FS", lag: 0 },
    { pred: "HP7060", succ: "HP7070", type: "FS", lag: 0 },
    { pred: "HP5140", succ: "HP7080", type: "FS", lag: 0 },
    { pred: "HP7070", succ: "HP7080", type: "FS", lag: 0 },
    { pred: "HP3100", succ: "HP7090", type: "FS", lag: 0 },
    // Commissioning & Closeout
    { pred: "HP7070", succ: "HP8010", type: "FS", lag: 0 },
    { pred: "HP7080", succ: "HP8010", type: "FS", lag: 0 },
    { pred: "HP8010", succ: "HP8020", type: "FS", lag: 0 },
    { pred: "HP8020", succ: "HP8030", type: "FS", lag: 0 },
    { pred: "HP8030", succ: "HP8040", type: "FS", lag: 0 },
    { pred: "HP8040", succ: "HP8050", type: "FS", lag: 0 },
    { pred: "HP8050", succ: "HP8060", type: "FS", lag: 0 },
    { pred: "HP8060", succ: "HP8070", type: "FS", lag: 0 },
    { pred: "HP8070", succ: "HP8080", type: "FS", lag: 0 },
    { pred: "HP7090", succ: "HP8070", type: "FS", lag: 0 },
    { pred: "HP8080", succ: "HP8090", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Sitework", "Foundations", "Structure", "Enclosure", "MEP Rough", "Finishes", "MEP Trim", "Commissioning", "Closeout"] },
    { name: "Trade", values: ["General", "Earthwork", "Concrete", "Structural Steel", "Masonry", "Roofing", "Curtain Wall", "Electrical", "Plumbing", "Medical Gas", "HVAC", "Fire Protection", "Drywall", "Flooring", "Paint", "Casework", "Elevator"] },
    { name: "Area", values: ["Site", "Building A", "Building B", "OR Suite", "ED", "Patient Rooms", "Admin", "Lab", "Pharmacy", "Lobby"] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// WATER TREATMENT PLANT — $2M–$4M Municipal Water/Wastewater
// 12–18 month schedule, 70+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const waterTreatmentTemplate: ScheduleTemplate = {
  name: "Water Treatment Plant",
  description: "Municipal water/wastewater treatment facility ($2M–$4M) — heavy civil, process piping, equipment installation, and commissioning",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction & Procurement", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "2.0", name: "Sitework & Earthwork", parentCode: null, sortOrder: 20, color: "#84cc16", textColor: "#ffffff" },
    { code: "3.0", name: "Concrete & Structures", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "3.1", name: "Process Basins & Tanks", parentCode: "3.0", sortOrder: 31, color: "#a78bfa", textColor: "#000000" },
    { code: "3.2", name: "Control Building", parentCode: "3.0", sortOrder: 32, color: "#c4b5fd", textColor: "#000000" },
    { code: "4.0", name: "Process Piping", parentCode: null, sortOrder: 40, color: "#3b82f6", textColor: "#ffffff" },
    { code: "5.0", name: "Mechanical Equipment", parentCode: null, sortOrder: 50, color: "#06b6d4", textColor: "#ffffff" },
    { code: "6.0", name: "Electrical & I&C", parentCode: null, sortOrder: 60, color: "#10b981", textColor: "#ffffff" },
    { code: "6.1", name: "Power Distribution", parentCode: "6.0", sortOrder: 61, color: "#34d399", textColor: "#000000" },
    { code: "6.2", name: "Instrumentation & Controls", parentCode: "6.0", sortOrder: 62, color: "#6ee7b7", textColor: "#000000" },
    { code: "7.0", name: "Building Finishes", parentCode: null, sortOrder: 70, color: "#14b8a6", textColor: "#ffffff" },
    { code: "8.0", name: "Site Restoration", parentCode: null, sortOrder: 80, color: "#84cc16", textColor: "#ffffff" },
    { code: "9.0", name: "Startup & Commissioning", parentCode: null, sortOrder: 90, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Construction
    { activityId: "WT1010", name: "Pre-Construction Meeting", duration: 1, wbs: "1.0" },
    { activityId: "WT1020", name: "Submit Building & Environmental Permits", duration: 5, wbs: "1.0" },
    { activityId: "WT1030", name: "Permit Review & Approval", duration: 30, wbs: "1.0" },
    { activityId: "WT1040", name: "Submit Process Equipment Shop Drawings", duration: 10, wbs: "1.0" },
    { activityId: "WT1050", name: "Process Equipment Review & Approval", duration: 14, wbs: "1.0" },
    { activityId: "WT1060", name: "Order Process Equipment (Pumps, Blowers, UV)", duration: 3, wbs: "1.0" },
    { activityId: "WT1070", name: "Process Equipment Lead Time", duration: 70, wbs: "1.0" },
    { activityId: "WT1080", name: "Order MCC & Switchgear", duration: 3, wbs: "1.0" },
    { activityId: "WT1090", name: "MCC & Switchgear Lead Time", duration: 56, wbs: "1.0" },
    { activityId: "WT1100", name: "Submit Pipe & Valve Shop Drawings", duration: 7, wbs: "1.0" },
    { activityId: "WT1110", name: "Pipe & Valve Review", duration: 10, wbs: "1.0" },
    // 2.0 Sitework
    { activityId: "WT2010", name: "Mobilization & Erosion Control", duration: 3, wbs: "2.0" },
    { activityId: "WT2020", name: "Site Clearing & Stripping", duration: 5, wbs: "2.0" },
    { activityId: "WT2030", name: "Mass Excavation — Basin Areas", duration: 10, wbs: "2.0" },
    { activityId: "WT2040", name: "Dewatering (if required)", duration: 7, wbs: "2.0" },
    { activityId: "WT2050", name: "Structural Fill & Compaction", duration: 7, wbs: "2.0" },
    { activityId: "WT2060", name: "Underground Utilities — Storm & Sanitary", duration: 10, wbs: "2.0" },
    { activityId: "WT2070", name: "Underground Utilities — Process Piping", duration: 12, wbs: "2.0" },
    // 3.0 Concrete & Structures
    { activityId: "WT3010", name: "Foundations — Control Building", duration: 7, wbs: "3.2" },
    { activityId: "WT3020", name: "Foundations — Equipment Pads", duration: 7, wbs: "3.1" },
    { activityId: "WT3030", name: "Basin Walls — Rebar & Formwork", duration: 15, wbs: "3.1" },
    { activityId: "WT3040", name: "Basin Walls — Concrete Pour & Cure", duration: 10, wbs: "3.1" },
    { activityId: "WT3050", name: "Basin Slabs — Pour & Cure", duration: 7, wbs: "3.1" },
    { activityId: "WT3060", name: "Clarifier / Settling Tank Construction", duration: 15, wbs: "3.1" },
    { activityId: "WT3070", name: "Filter Basin Construction", duration: 12, wbs: "3.1" },
    { activityId: "WT3080", name: "Chlorine Contact Basin", duration: 10, wbs: "3.1" },
    { activityId: "WT3090", name: "Control Building — CMU Walls", duration: 10, wbs: "3.2" },
    { activityId: "WT3100", name: "Control Building — Roof Structure", duration: 7, wbs: "3.2" },
    { activityId: "WT3110", name: "Hydrostatic Testing — All Basins", duration: 7, wbs: "3.1" },
    // 4.0 Process Piping
    { activityId: "WT4010", name: "Yard Piping — Influent & Effluent", duration: 12, wbs: "4.0" },
    { activityId: "WT4020", name: "Process Piping — Between Basins", duration: 10, wbs: "4.0" },
    { activityId: "WT4030", name: "Chemical Feed Piping", duration: 7, wbs: "4.0" },
    { activityId: "WT4040", name: "Sludge Piping", duration: 7, wbs: "4.0" },
    { activityId: "WT4050", name: "Valves & Actuators Installation", duration: 7, wbs: "4.0" },
    { activityId: "WT4060", name: "Pipe Supports & Hangers", duration: 5, wbs: "4.0" },
    { activityId: "WT4070", name: "Pressure Testing — All Process Piping", duration: 5, wbs: "4.0" },
    // 5.0 Mechanical Equipment
    { activityId: "WT5010", name: "Pump Installation — Raw Water & Process", duration: 7, wbs: "5.0" },
    { activityId: "WT5020", name: "Blower / Aerator Installation", duration: 5, wbs: "5.0" },
    { activityId: "WT5030", name: "Clarifier Mechanism Installation", duration: 7, wbs: "5.0" },
    { activityId: "WT5040", name: "Filter Media & Underdrain Installation", duration: 7, wbs: "5.0" },
    { activityId: "WT5050", name: "UV Disinfection System Install", duration: 5, wbs: "5.0" },
    { activityId: "WT5060", name: "Chemical Storage & Feed Systems", duration: 7, wbs: "5.0" },
    { activityId: "WT5070", name: "HVAC — Control Building", duration: 5, wbs: "5.0" },
    { activityId: "WT5080", name: "Crane / Hoist Installation", duration: 3, wbs: "5.0" },
    // 6.0 Electrical & I&C
    { activityId: "WT6010", name: "Main Switchgear & MCC Installation", duration: 7, wbs: "6.1" },
    { activityId: "WT6020", name: "Power Distribution — Conduit & Wire", duration: 12, wbs: "6.1" },
    { activityId: "WT6030", name: "Emergency Generator & ATS", duration: 5, wbs: "6.1" },
    { activityId: "WT6040", name: "Lighting — Interior & Exterior", duration: 7, wbs: "6.1" },
    { activityId: "WT6050", name: "Instrumentation — Level, Flow, Pressure", duration: 10, wbs: "6.2" },
    { activityId: "WT6060", name: "SCADA System — PLC & HMI", duration: 10, wbs: "6.2" },
    { activityId: "WT6070", name: "Control Panel Wiring & Terminations", duration: 7, wbs: "6.2" },
    { activityId: "WT6080", name: "VFD Installation & Programming", duration: 5, wbs: "6.2" },
    // 7.0 Building Finishes
    { activityId: "WT7010", name: "Control Building — Interior Finishes", duration: 7, wbs: "7.0" },
    { activityId: "WT7020", name: "Control Building — Plumbing Trim", duration: 3, wbs: "7.0" },
    { activityId: "WT7030", name: "Handrails, Grating & Safety Equipment", duration: 5, wbs: "7.0" },
    { activityId: "WT7040", name: "Signage & Safety Labeling", duration: 2, wbs: "7.0" },
    // 8.0 Site Restoration
    { activityId: "WT8010", name: "Final Grading & Drainage", duration: 5, wbs: "8.0" },
    { activityId: "WT8020", name: "Access Roads & Paving", duration: 7, wbs: "8.0" },
    { activityId: "WT8030", name: "Fencing & Gates", duration: 5, wbs: "8.0" },
    { activityId: "WT8040", name: "Landscaping & Seeding", duration: 5, wbs: "8.0" },
    // 9.0 Startup & Commissioning
    { activityId: "WT9010", name: "Electrical Energization & Testing", duration: 5, wbs: "9.0" },
    { activityId: "WT9020", name: "Equipment Startup — Pumps & Blowers", duration: 7, wbs: "9.0" },
    { activityId: "WT9030", name: "Process Startup — Fill & Seed", duration: 14, wbs: "9.0" },
    { activityId: "WT9040", name: "SCADA Commissioning & Loop Checks", duration: 7, wbs: "9.0" },
    { activityId: "WT9050", name: "Performance Testing (30-day)", duration: 30, wbs: "9.0" },
    { activityId: "WT9060", name: "Operator Training", duration: 5, wbs: "9.0" },
    { activityId: "WT9070", name: "Punch List & Corrections", duration: 10, wbs: "9.0" },
    { activityId: "WT9080", name: "Final Acceptance", duration: 0, wbs: "9.0", activityType: "milestone" },
  ],
  relationships: [
    { pred: "WT1010", succ: "WT1020", type: "FS", lag: 0 },
    { pred: "WT1020", succ: "WT1030", type: "FS", lag: 0 },
    { pred: "WT1010", succ: "WT1040", type: "FS", lag: 0 },
    { pred: "WT1040", succ: "WT1050", type: "FS", lag: 0 },
    { pred: "WT1050", succ: "WT1060", type: "FS", lag: 0 },
    { pred: "WT1060", succ: "WT1070", type: "FS", lag: 0 },
    { pred: "WT1010", succ: "WT1080", type: "FS", lag: 0 },
    { pred: "WT1080", succ: "WT1090", type: "FS", lag: 0 },
    { pred: "WT1010", succ: "WT1100", type: "FS", lag: 0 },
    { pred: "WT1100", succ: "WT1110", type: "FS", lag: 0 },
    { pred: "WT1030", succ: "WT2010", type: "FS", lag: 0 },
    { pred: "WT2010", succ: "WT2020", type: "FS", lag: 0 },
    { pred: "WT2020", succ: "WT2030", type: "FS", lag: 0 },
    { pred: "WT2030", succ: "WT2040", type: "SS", lag: 3 },
    { pred: "WT2030", succ: "WT2050", type: "FS", lag: 0 },
    { pred: "WT2050", succ: "WT2060", type: "FS", lag: 0 },
    { pred: "WT2050", succ: "WT2070", type: "SS", lag: 5 },
    { pred: "WT2050", succ: "WT3010", type: "FS", lag: 0 },
    { pred: "WT2050", succ: "WT3020", type: "FS", lag: 0 },
    { pred: "WT2060", succ: "WT3030", type: "FS", lag: 0 },
    { pred: "WT3020", succ: "WT3030", type: "FS", lag: 0 },
    { pred: "WT3030", succ: "WT3040", type: "FS", lag: 0 },
    { pred: "WT3040", succ: "WT3050", type: "FS", lag: 0 },
    { pred: "WT3050", succ: "WT3060", type: "FS", lag: 0 },
    { pred: "WT3060", succ: "WT3070", type: "SS", lag: 5 },
    { pred: "WT3070", succ: "WT3080", type: "SS", lag: 5 },
    { pred: "WT3010", succ: "WT3090", type: "FS", lag: 0 },
    { pred: "WT3090", succ: "WT3100", type: "FS", lag: 0 },
    { pred: "WT3080", succ: "WT3110", type: "FS", lag: 0 },
    { pred: "WT1110", succ: "WT4010", type: "FS", lag: 0 },
    { pred: "WT3110", succ: "WT4010", type: "FS", lag: 0 },
    { pred: "WT4010", succ: "WT4020", type: "SS", lag: 5 },
    { pred: "WT4020", succ: "WT4030", type: "SS", lag: 3 },
    { pred: "WT4020", succ: "WT4040", type: "SS", lag: 3 },
    { pred: "WT4030", succ: "WT4050", type: "FS", lag: 0 },
    { pred: "WT4040", succ: "WT4050", type: "FS", lag: 0 },
    { pred: "WT4010", succ: "WT4060", type: "SS", lag: 5 },
    { pred: "WT4050", succ: "WT4070", type: "FS", lag: 0 },
    { pred: "WT1070", succ: "WT5010", type: "FS", lag: 0 },
    { pred: "WT4070", succ: "WT5010", type: "FS", lag: 0 },
    { pred: "WT5010", succ: "WT5020", type: "SS", lag: 3 },
    { pred: "WT3060", succ: "WT5030", type: "FS", lag: 0 },
    { pred: "WT3070", succ: "WT5040", type: "FS", lag: 0 },
    { pred: "WT5010", succ: "WT5050", type: "SS", lag: 3 },
    { pred: "WT4030", succ: "WT5060", type: "FS", lag: 0 },
    { pred: "WT3100", succ: "WT5070", type: "FS", lag: 0 },
    { pred: "WT3060", succ: "WT5080", type: "FS", lag: 0 },
    { pred: "WT1090", succ: "WT6010", type: "FS", lag: 0 },
    { pred: "WT3100", succ: "WT6010", type: "FS", lag: 0 },
    { pred: "WT6010", succ: "WT6020", type: "FS", lag: 0 },
    { pred: "WT6010", succ: "WT6030", type: "SS", lag: 3 },
    { pred: "WT6020", succ: "WT6040", type: "SS", lag: 5 },
    { pred: "WT5010", succ: "WT6050", type: "FS", lag: 0 },
    { pred: "WT6050", succ: "WT6060", type: "SS", lag: 5 },
    { pred: "WT6060", succ: "WT6070", type: "SS", lag: 3 },
    { pred: "WT5010", succ: "WT6080", type: "FS", lag: 0 },
    { pred: "WT5070", succ: "WT7010", type: "FS", lag: 0 },
    { pred: "WT7010", succ: "WT7020", type: "SS", lag: 3 },
    { pred: "WT3110", succ: "WT7030", type: "FS", lag: 0 },
    { pred: "WT7030", succ: "WT7040", type: "FS", lag: 0 },
    { pred: "WT7040", succ: "WT8010", type: "FS", lag: 0 },
    { pred: "WT8010", succ: "WT8020", type: "FS", lag: 0 },
    { pred: "WT8020", succ: "WT8030", type: "SS", lag: 3 },
    { pred: "WT8030", succ: "WT8040", type: "FS", lag: 0 },
    { pred: "WT6020", succ: "WT9010", type: "FS", lag: 0 },
    { pred: "WT6080", succ: "WT9010", type: "FS", lag: 0 },
    { pred: "WT9010", succ: "WT9020", type: "FS", lag: 0 },
    { pred: "WT9020", succ: "WT9030", type: "FS", lag: 0 },
    { pred: "WT6070", succ: "WT9040", type: "FS", lag: 0 },
    { pred: "WT9020", succ: "WT9040", type: "SS", lag: 3 },
    { pred: "WT9030", succ: "WT9050", type: "FS", lag: 0 },
    { pred: "WT9040", succ: "WT9050", type: "FS", lag: 0 },
    { pred: "WT9050", succ: "WT9060", type: "FS", lag: 0 },
    { pred: "WT9050", succ: "WT9070", type: "SS", lag: 10 },
    { pred: "WT9070", succ: "WT9080", type: "FS", lag: 0 },
    { pred: "WT9060", succ: "WT9080", type: "FS", lag: 0 },
    { pred: "WT8040", succ: "WT9080", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Sitework", "Concrete", "Piping", "Equipment", "Electrical", "I&C", "Finishes", "Startup", "Closeout"] },
    { name: "Trade", values: ["General", "Earthwork", "Concrete", "Piping", "Mechanical", "Electrical", "I&C", "HVAC", "Structural"] },
    { name: "System", values: ["Influent", "Clarification", "Filtration", "Disinfection", "Chemical Feed", "Sludge", "Effluent", "Controls", "Building"] },
  ],
};


// ═══════════════════════════════════════════════════════════════════════════════
// ELECTRICAL (TRADE-SPECIFIC) — $500K–$2M Commercial Electrical Package
// 10–16 week schedule, 55+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const electricalTemplate: ScheduleTemplate = {
  name: "Electrical (Trade-Specific)",
  description: "Electrical contractor schedule for commercial building ($500K–$2M) — power distribution, lighting, fire alarm, low voltage, and commissioning",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction & Submittals", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "2.0", name: "Temporary Power & Site Electrical", parentCode: null, sortOrder: 20, color: "#84cc16", textColor: "#ffffff" },
    { code: "3.0", name: "Underground & Slab", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "4.0", name: "Rough-In — Power Distribution", parentCode: null, sortOrder: 40, color: "#3b82f6", textColor: "#ffffff" },
    { code: "4.1", name: "Main Service & Switchgear", parentCode: "4.0", sortOrder: 41, color: "#60a5fa", textColor: "#000000" },
    { code: "4.2", name: "Branch Circuits & Panels", parentCode: "4.0", sortOrder: 42, color: "#93c5fd", textColor: "#000000" },
    { code: "4.3", name: "Motor Connections & Disconnects", parentCode: "4.0", sortOrder: 43, color: "#bfdbfe", textColor: "#000000" },
    { code: "5.0", name: "Rough-In — Low Voltage", parentCode: null, sortOrder: 50, color: "#06b6d4", textColor: "#ffffff" },
    { code: "5.1", name: "Data & Telecom", parentCode: "5.0", sortOrder: 51, color: "#22d3ee", textColor: "#000000" },
    { code: "5.2", name: "Fire Alarm", parentCode: "5.0", sortOrder: 52, color: "#67e8f9", textColor: "#000000" },
    { code: "5.3", name: "Security & AV", parentCode: "5.0", sortOrder: 53, color: "#a5f3fc", textColor: "#000000" },
    { code: "6.0", name: "Lighting", parentCode: null, sortOrder: 60, color: "#10b981", textColor: "#ffffff" },
    { code: "7.0", name: "Trim & Devices", parentCode: null, sortOrder: 70, color: "#14b8a6", textColor: "#ffffff" },
    { code: "8.0", name: "Testing & Commissioning", parentCode: null, sortOrder: 80, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Construction
    { activityId: "EL1010", name: "Electrical Pre-Con & Coordination Meeting", duration: 1, wbs: "1.0" },
    { activityId: "EL1020", name: "Submit Switchgear & Panel Shop Drawings", duration: 7, wbs: "1.0" },
    { activityId: "EL1030", name: "Switchgear Shop Drawing Review", duration: 10, wbs: "1.0" },
    { activityId: "EL1040", name: "Submit Light Fixture Schedule & Cuts", duration: 5, wbs: "1.0" },
    { activityId: "EL1050", name: "Light Fixture Review & Approval", duration: 10, wbs: "1.0" },
    { activityId: "EL1060", name: "Submit Fire Alarm Shop Drawings", duration: 7, wbs: "1.0" },
    { activityId: "EL1070", name: "Fire Alarm Review & Approval", duration: 10, wbs: "1.0" },
    { activityId: "EL1080", name: "Order Switchgear & MCC", duration: 3, wbs: "1.0" },
    { activityId: "EL1090", name: "Switchgear Lead Time & Delivery", duration: 42, wbs: "1.0" },
    { activityId: "EL1100", name: "Order Light Fixtures", duration: 3, wbs: "1.0" },
    { activityId: "EL1110", name: "Light Fixture Lead Time & Delivery", duration: 28, wbs: "1.0" },
    { activityId: "EL1120", name: "Order Generator (if in scope)", duration: 3, wbs: "1.0" },
    { activityId: "EL1130", name: "Generator Lead Time & Delivery", duration: 49, wbs: "1.0" },
    // 2.0 Temporary Power
    { activityId: "EL2010", name: "Install Temporary Power Panel", duration: 2, wbs: "2.0" },
    { activityId: "EL2020", name: "Temporary Lighting & GFI Circuits", duration: 3, wbs: "2.0" },
    { activityId: "EL2030", name: "Site Lighting — Poles & Fixtures", duration: 5, wbs: "2.0" },
    // 3.0 Underground
    { activityId: "EL3010", name: "Underground Conduit — Building Entry", duration: 5, wbs: "3.0" },
    { activityId: "EL3020", name: "Underground Conduit — Parking & Site", duration: 7, wbs: "3.0" },
    { activityId: "EL3030", name: "Slab Conduit — Floor Boxes & Stubs", duration: 5, wbs: "3.0" },
    { activityId: "EL3040", name: "Grounding Electrode System", duration: 3, wbs: "3.0" },
    // 4.0 Power Distribution
    { activityId: "EL4010", name: "Main Switchgear Installation", duration: 5, wbs: "4.1" },
    { activityId: "EL4020", name: "Main Feeder Conduit & Wire Pull", duration: 7, wbs: "4.1" },
    { activityId: "EL4030", name: "Distribution Panels — Set & Land", duration: 5, wbs: "4.1" },
    { activityId: "EL4040", name: "Generator & ATS Installation", duration: 5, wbs: "4.1" },
    { activityId: "EL4050", name: "Branch Panel Installation", duration: 5, wbs: "4.2" },
    { activityId: "EL4060", name: "Branch Circuit Conduit — Phase 1 (Floors 1-2)", duration: 10, wbs: "4.2" },
    { activityId: "EL4070", name: "Branch Circuit Conduit — Phase 2 (Floors 3+)", duration: 8, wbs: "4.2" },
    { activityId: "EL4080", name: "Branch Circuit Wire Pull — Phase 1", duration: 7, wbs: "4.2" },
    { activityId: "EL4090", name: "Branch Circuit Wire Pull — Phase 2", duration: 5, wbs: "4.2" },
    { activityId: "EL4100", name: "Motor Connections & Disconnects — HVAC", duration: 5, wbs: "4.3" },
    { activityId: "EL4110", name: "Motor Connections — Elevator & Misc", duration: 3, wbs: "4.3" },
    { activityId: "EL4120", name: "VFD Installation & Wiring", duration: 4, wbs: "4.3" },
    // 5.0 Low Voltage
    { activityId: "EL5010", name: "Data Backbone — MDF/IDF Rooms", duration: 5, wbs: "5.1" },
    { activityId: "EL5020", name: "Data Cabling — Horizontal Runs", duration: 10, wbs: "5.1" },
    { activityId: "EL5030", name: "Data Terminations & Testing", duration: 5, wbs: "5.1" },
    { activityId: "EL5040", name: "Fire Alarm — Conduit & Wiring", duration: 7, wbs: "5.2" },
    { activityId: "EL5050", name: "Fire Alarm — Device Installation", duration: 5, wbs: "5.2" },
    { activityId: "EL5060", name: "Fire Alarm — Panel Programming", duration: 3, wbs: "5.2" },
    { activityId: "EL5070", name: "Security — Access Control Wiring", duration: 5, wbs: "5.3" },
    { activityId: "EL5080", name: "Security — Camera & Intercom Wiring", duration: 5, wbs: "5.3" },
    { activityId: "EL5090", name: "AV Rough-In — Conference Rooms", duration: 4, wbs: "5.3" },
    // 6.0 Lighting
    { activityId: "EL6010", name: "Recessed Light Fixture Rough-In", duration: 7, wbs: "6.0" },
    { activityId: "EL6020", name: "Pendant & Surface Mount Fixture Install", duration: 5, wbs: "6.0" },
    { activityId: "EL6030", name: "Emergency & Exit Lighting", duration: 4, wbs: "6.0" },
    { activityId: "EL6040", name: "Exterior Lighting — Wall Packs & Bollards", duration: 4, wbs: "6.0" },
    { activityId: "EL6050", name: "Lighting Controls & Dimming", duration: 4, wbs: "6.0" },
    { activityId: "EL6060", name: "Lighting Control Programming", duration: 3, wbs: "6.0" },
    // 7.0 Trim & Devices
    { activityId: "EL7010", name: "Receptacles & Switches — Install", duration: 5, wbs: "7.0" },
    { activityId: "EL7020", name: "Cover Plates & Device Trim", duration: 3, wbs: "7.0" },
    { activityId: "EL7030", name: "Panel Labeling & Circuit Directory", duration: 2, wbs: "7.0" },
    { activityId: "EL7040", name: "Data Rack Trim & Patch Panels", duration: 3, wbs: "7.0" },
    // 8.0 Testing & Commissioning
    { activityId: "EL8010", name: "Megger Testing — All Feeders", duration: 3, wbs: "8.0" },
    { activityId: "EL8020", name: "Switchgear Energization & Testing", duration: 3, wbs: "8.0" },
    { activityId: "EL8030", name: "Circuit Verification & Labeling", duration: 5, wbs: "8.0" },
    { activityId: "EL8040", name: "Fire Alarm Acceptance Testing", duration: 3, wbs: "8.0" },
    { activityId: "EL8050", name: "Generator Load Bank Test", duration: 2, wbs: "8.0" },
    { activityId: "EL8060", name: "Lighting Level Verification", duration: 2, wbs: "8.0" },
    { activityId: "EL8070", name: "Punch List & Corrections", duration: 5, wbs: "8.0" },
    { activityId: "EL8080", name: "As-Built Drawings & O&M Manuals", duration: 3, wbs: "8.0" },
    { activityId: "EL8090", name: "Substantial Completion", duration: 0, wbs: "8.0", activityType: "milestone" },
  ],
  relationships: [
    { pred: "EL1010", succ: "EL1020", type: "FS", lag: 0 },
    { pred: "EL1020", succ: "EL1030", type: "FS", lag: 0 },
    { pred: "EL1010", succ: "EL1040", type: "FS", lag: 0 },
    { pred: "EL1040", succ: "EL1050", type: "FS", lag: 0 },
    { pred: "EL1010", succ: "EL1060", type: "FS", lag: 0 },
    { pred: "EL1060", succ: "EL1070", type: "FS", lag: 0 },
    { pred: "EL1030", succ: "EL1080", type: "FS", lag: 0 },
    { pred: "EL1080", succ: "EL1090", type: "FS", lag: 0 },
    { pred: "EL1050", succ: "EL1100", type: "FS", lag: 0 },
    { pred: "EL1100", succ: "EL1110", type: "FS", lag: 0 },
    { pred: "EL1010", succ: "EL1120", type: "FS", lag: 0 },
    { pred: "EL1120", succ: "EL1130", type: "FS", lag: 0 },
    { pred: "EL1010", succ: "EL2010", type: "FS", lag: 0 },
    { pred: "EL2010", succ: "EL2020", type: "FS", lag: 0 },
    { pred: "EL2010", succ: "EL2030", type: "SS", lag: 2 },
    { pred: "EL2010", succ: "EL3010", type: "FS", lag: 0 },
    { pred: "EL3010", succ: "EL3020", type: "SS", lag: 2 },
    { pred: "EL3010", succ: "EL3030", type: "SS", lag: 2 },
    { pred: "EL3010", succ: "EL3040", type: "FS", lag: 0 },
    { pred: "EL1090", succ: "EL4010", type: "FS", lag: 0 },
    { pred: "EL3040", succ: "EL4010", type: "FS", lag: 0 },
    { pred: "EL4010", succ: "EL4020", type: "FS", lag: 0 },
    { pred: "EL4020", succ: "EL4030", type: "FS", lag: 0 },
    { pred: "EL1130", succ: "EL4040", type: "FS", lag: 0 },
    { pred: "EL4010", succ: "EL4040", type: "SS", lag: 3 },
    { pred: "EL4030", succ: "EL4050", type: "FS", lag: 0 },
    { pred: "EL4050", succ: "EL4060", type: "FS", lag: 0 },
    { pred: "EL4060", succ: "EL4070", type: "FS", lag: 0 },
    { pred: "EL4060", succ: "EL4080", type: "SS", lag: 5 },
    { pred: "EL4070", succ: "EL4090", type: "SS", lag: 3 },
    { pred: "EL4080", succ: "EL4100", type: "FS", lag: 0 },
    { pred: "EL4100", succ: "EL4110", type: "SS", lag: 2 },
    { pred: "EL4100", succ: "EL4120", type: "SS", lag: 2 },
    { pred: "EL4030", succ: "EL5010", type: "FS", lag: 0 },
    { pred: "EL5010", succ: "EL5020", type: "FS", lag: 0 },
    { pred: "EL5020", succ: "EL5030", type: "FS", lag: 0 },
    { pred: "EL1070", succ: "EL5040", type: "FS", lag: 0 },
    { pred: "EL4060", succ: "EL5040", type: "SS", lag: 3 },
    { pred: "EL5040", succ: "EL5050", type: "FS", lag: 0 },
    { pred: "EL5050", succ: "EL5060", type: "FS", lag: 0 },
    { pred: "EL5020", succ: "EL5070", type: "SS", lag: 3 },
    { pred: "EL5070", succ: "EL5080", type: "SS", lag: 2 },
    { pred: "EL5020", succ: "EL5090", type: "SS", lag: 3 },
    { pred: "EL1110", succ: "EL6010", type: "FS", lag: 0 },
    { pred: "EL4080", succ: "EL6010", type: "FS", lag: 0 },
    { pred: "EL6010", succ: "EL6020", type: "SS", lag: 3 },
    { pred: "EL6010", succ: "EL6030", type: "SS", lag: 3 },
    { pred: "EL6010", succ: "EL6040", type: "SS", lag: 3 },
    { pred: "EL6020", succ: "EL6050", type: "FS", lag: 0 },
    { pred: "EL6050", succ: "EL6060", type: "FS", lag: 0 },
    { pred: "EL4090", succ: "EL7010", type: "FS", lag: 0 },
    { pred: "EL6060", succ: "EL7010", type: "FS", lag: 0 },
    { pred: "EL7010", succ: "EL7020", type: "FS", lag: 0 },
    { pred: "EL7020", succ: "EL7030", type: "FS", lag: 0 },
    { pred: "EL5030", succ: "EL7040", type: "FS", lag: 0 },
    { pred: "EL4020", succ: "EL8010", type: "FS", lag: 0 },
    { pred: "EL7030", succ: "EL8020", type: "FS", lag: 0 },
    { pred: "EL8010", succ: "EL8020", type: "FS", lag: 0 },
    { pred: "EL8020", succ: "EL8030", type: "FS", lag: 0 },
    { pred: "EL5060", succ: "EL8040", type: "FS", lag: 0 },
    { pred: "EL8030", succ: "EL8040", type: "FS", lag: 0 },
    { pred: "EL4040", succ: "EL8050", type: "FS", lag: 0 },
    { pred: "EL8030", succ: "EL8050", type: "FS", lag: 0 },
    { pred: "EL6060", succ: "EL8060", type: "FS", lag: 0 },
    { pred: "EL8040", succ: "EL8070", type: "FS", lag: 0 },
    { pred: "EL8050", succ: "EL8070", type: "FS", lag: 0 },
    { pred: "EL8060", succ: "EL8070", type: "FS", lag: 0 },
    { pred: "EL8070", succ: "EL8080", type: "FS", lag: 0 },
    { pred: "EL8080", succ: "EL8090", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Temp Power", "Underground", "Rough-In", "Low Voltage", "Lighting", "Trim", "Testing", "Closeout"] },
    { name: "System", values: ["Power Distribution", "Branch Circuits", "Motors & VFDs", "Data/Telecom", "Fire Alarm", "Security", "AV", "Lighting", "Emergency Power", "Grounding"] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// HVAC / MECHANICAL (TRADE-SPECIFIC) — $500K–$2M Commercial HVAC Package
// 10–16 week schedule, 50+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const hvacTemplate: ScheduleTemplate = {
  name: "HVAC / Mechanical (Trade-Specific)",
  description: "HVAC/mechanical contractor schedule for commercial building ($500K–$2M) — ductwork, piping, equipment, controls, TAB, and commissioning",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction & Procurement", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "2.0", name: "Sheet Metal — Ductwork", parentCode: null, sortOrder: 20, color: "#3b82f6", textColor: "#ffffff" },
    { code: "2.1", name: "Main Trunk Lines", parentCode: "2.0", sortOrder: 21, color: "#60a5fa", textColor: "#000000" },
    { code: "2.2", name: "Branch Ductwork", parentCode: "2.0", sortOrder: 22, color: "#93c5fd", textColor: "#000000" },
    { code: "3.0", name: "Piping", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "3.1", name: "Hydronic Piping", parentCode: "3.0", sortOrder: 31, color: "#a78bfa", textColor: "#000000" },
    { code: "3.2", name: "Refrigerant Piping", parentCode: "3.0", sortOrder: 32, color: "#c4b5fd", textColor: "#000000" },
    { code: "3.3", name: "Condensate & Drain Piping", parentCode: "3.0", sortOrder: 33, color: "#ddd6fe", textColor: "#000000" },
    { code: "4.0", name: "Equipment Installation", parentCode: null, sortOrder: 40, color: "#06b6d4", textColor: "#ffffff" },
    { code: "5.0", name: "Insulation", parentCode: null, sortOrder: 50, color: "#10b981", textColor: "#ffffff" },
    { code: "6.0", name: "Controls & BAS", parentCode: null, sortOrder: 60, color: "#14b8a6", textColor: "#ffffff" },
    { code: "7.0", name: "Trim & Finish", parentCode: null, sortOrder: 70, color: "#84cc16", textColor: "#ffffff" },
    { code: "8.0", name: "Testing & Commissioning", parentCode: null, sortOrder: 80, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Con
    { activityId: "HV1010", name: "HVAC Pre-Con & Coordination Meeting", duration: 1, wbs: "1.0" },
    { activityId: "HV1020", name: "Submit Equipment Shop Drawings (AHU, RTU, Chiller)", duration: 7, wbs: "1.0" },
    { activityId: "HV1030", name: "Equipment Shop Drawing Review", duration: 14, wbs: "1.0" },
    { activityId: "HV1040", name: "Submit Ductwork Shop Drawings", duration: 7, wbs: "1.0" },
    { activityId: "HV1050", name: "Ductwork Shop Drawing Review", duration: 10, wbs: "1.0" },
    { activityId: "HV1060", name: "Submit Controls Submittals", duration: 5, wbs: "1.0" },
    { activityId: "HV1070", name: "Controls Submittal Review", duration: 10, wbs: "1.0" },
    { activityId: "HV1080", name: "Order AHU / RTU Equipment", duration: 3, wbs: "1.0" },
    { activityId: "HV1090", name: "AHU / RTU Lead Time & Delivery", duration: 56, wbs: "1.0" },
    { activityId: "HV1100", name: "Order Chiller / Boiler", duration: 3, wbs: "1.0" },
    { activityId: "HV1110", name: "Chiller / Boiler Lead Time & Delivery", duration: 63, wbs: "1.0" },
    { activityId: "HV1120", name: "Order VAV Boxes & Terminal Units", duration: 3, wbs: "1.0" },
    { activityId: "HV1130", name: "VAV Box Lead Time & Delivery", duration: 28, wbs: "1.0" },
    { activityId: "HV1140", name: "Fabricate Ductwork (shop)", duration: 14, wbs: "1.0" },
    // 2.0 Ductwork
    { activityId: "HV2010", name: "Main Trunk Ductwork — Basement / Mech Room", duration: 7, wbs: "2.1" },
    { activityId: "HV2020", name: "Main Trunk Ductwork — Risers & Shafts", duration: 5, wbs: "2.1" },
    { activityId: "HV2030", name: "Main Trunk Ductwork — Floor Distribution", duration: 10, wbs: "2.1" },
    { activityId: "HV2040", name: "Branch Ductwork — Phase 1 (Floors 1-2)", duration: 10, wbs: "2.2" },
    { activityId: "HV2050", name: "Branch Ductwork — Phase 2 (Floors 3+)", duration: 8, wbs: "2.2" },
    { activityId: "HV2060", name: "Exhaust Ductwork — Restrooms & Kitchen", duration: 5, wbs: "2.2" },
    { activityId: "HV2070", name: "Fire & Smoke Damper Installation", duration: 4, wbs: "2.2" },
    { activityId: "HV2080", name: "Duct Leak Testing", duration: 3, wbs: "2.2" },
    // 3.0 Piping
    { activityId: "HV3010", name: "Chilled Water Piping — Mains", duration: 7, wbs: "3.1" },
    { activityId: "HV3020", name: "Chilled Water Piping — Branch", duration: 7, wbs: "3.1" },
    { activityId: "HV3030", name: "Hot Water Piping — Mains", duration: 5, wbs: "3.1" },
    { activityId: "HV3040", name: "Hot Water Piping — Branch", duration: 5, wbs: "3.1" },
    { activityId: "HV3050", name: "Refrigerant Piping — VRF / Split Systems", duration: 7, wbs: "3.2" },
    { activityId: "HV3060", name: "Refrigerant Piping — Brazing & Testing", duration: 4, wbs: "3.2" },
    { activityId: "HV3070", name: "Condensate Drain Piping", duration: 4, wbs: "3.3" },
    { activityId: "HV3080", name: "Hydronic Pressure Testing", duration: 3, wbs: "3.1" },
    // 4.0 Equipment
    { activityId: "HV4010", name: "Set Chiller / Boiler on Pad", duration: 3, wbs: "4.0" },
    { activityId: "HV4020", name: "Set AHU / RTU on Curb", duration: 3, wbs: "4.0" },
    { activityId: "HV4030", name: "Install VAV Boxes & Terminal Units", duration: 7, wbs: "4.0" },
    { activityId: "HV4040", name: "Install Exhaust Fans", duration: 3, wbs: "4.0" },
    { activityId: "HV4050", name: "Install Pumps — CHW & HHW", duration: 3, wbs: "4.0" },
    { activityId: "HV4060", name: "Install Expansion Tanks & Air Separators", duration: 2, wbs: "4.0" },
    { activityId: "HV4070", name: "Install VRF Condensing Units", duration: 4, wbs: "4.0" },
    // 5.0 Insulation
    { activityId: "HV5010", name: "Duct Insulation — Supply", duration: 7, wbs: "5.0" },
    { activityId: "HV5020", name: "Pipe Insulation — Chilled Water", duration: 5, wbs: "5.0" },
    { activityId: "HV5030", name: "Pipe Insulation — Hot Water", duration: 4, wbs: "5.0" },
    { activityId: "HV5040", name: "Equipment Insulation Jackets", duration: 3, wbs: "5.0" },
    // 6.0 Controls
    { activityId: "HV6010", name: "BAS Controller Installation", duration: 5, wbs: "6.0" },
    { activityId: "HV6020", name: "Controls Wiring — Sensors & Actuators", duration: 7, wbs: "6.0" },
    { activityId: "HV6030", name: "Thermostat & Space Sensor Installation", duration: 4, wbs: "6.0" },
    { activityId: "HV6040", name: "BAS Programming & Graphics", duration: 7, wbs: "6.0" },
    { activityId: "HV6050", name: "Controls Point-to-Point Checkout", duration: 5, wbs: "6.0" },
    // 7.0 Trim
    { activityId: "HV7010", name: "Diffusers & Grilles — Install", duration: 5, wbs: "7.0" },
    { activityId: "HV7020", name: "Return Air Grilles", duration: 3, wbs: "7.0" },
    { activityId: "HV7030", name: "Access Doors & Panels", duration: 2, wbs: "7.0" },
    { activityId: "HV7040", name: "Equipment Labeling & Tagging", duration: 2, wbs: "7.0" },
    // 8.0 Testing
    { activityId: "HV8010", name: "Equipment Startup — AHU / RTU", duration: 3, wbs: "8.0" },
    { activityId: "HV8020", name: "Equipment Startup — Chiller / Boiler", duration: 3, wbs: "8.0" },
    { activityId: "HV8030", name: "Test & Balance (TAB) — Air Side", duration: 7, wbs: "8.0" },
    { activityId: "HV8040", name: "Test & Balance (TAB) — Water Side", duration: 5, wbs: "8.0" },
    { activityId: "HV8050", name: "Fire/Smoke Damper Functional Testing", duration: 3, wbs: "8.0" },
    { activityId: "HV8060", name: "BAS Functional Performance Testing", duration: 5, wbs: "8.0" },
    { activityId: "HV8070", name: "Punch List & Corrections", duration: 5, wbs: "8.0" },
    { activityId: "HV8080", name: "As-Built Drawings & O&M Manuals", duration: 3, wbs: "8.0" },
    { activityId: "HV8090", name: "Substantial Completion", duration: 0, wbs: "8.0", activityType: "milestone" },
  ],
  relationships: [
    { pred: "HV1010", succ: "HV1020", type: "FS", lag: 0 },
    { pred: "HV1020", succ: "HV1030", type: "FS", lag: 0 },
    { pred: "HV1010", succ: "HV1040", type: "FS", lag: 0 },
    { pred: "HV1040", succ: "HV1050", type: "FS", lag: 0 },
    { pred: "HV1010", succ: "HV1060", type: "FS", lag: 0 },
    { pred: "HV1060", succ: "HV1070", type: "FS", lag: 0 },
    { pred: "HV1030", succ: "HV1080", type: "FS", lag: 0 },
    { pred: "HV1080", succ: "HV1090", type: "FS", lag: 0 },
    { pred: "HV1030", succ: "HV1100", type: "FS", lag: 0 },
    { pred: "HV1100", succ: "HV1110", type: "FS", lag: 0 },
    { pred: "HV1030", succ: "HV1120", type: "FS", lag: 0 },
    { pred: "HV1120", succ: "HV1130", type: "FS", lag: 0 },
    { pred: "HV1050", succ: "HV1140", type: "FS", lag: 0 },
    { pred: "HV1140", succ: "HV2010", type: "FS", lag: 0 },
    { pred: "HV2010", succ: "HV2020", type: "FS", lag: 0 },
    { pred: "HV2020", succ: "HV2030", type: "FS", lag: 0 },
    { pred: "HV2030", succ: "HV2040", type: "SS", lag: 5 },
    { pred: "HV2040", succ: "HV2050", type: "FS", lag: 0 },
    { pred: "HV2030", succ: "HV2060", type: "SS", lag: 3 },
    { pred: "HV2040", succ: "HV2070", type: "SS", lag: 5 },
    { pred: "HV2050", succ: "HV2080", type: "FS", lag: 0 },
    { pred: "HV2070", succ: "HV2080", type: "FS", lag: 0 },
    { pred: "HV1110", succ: "HV4010", type: "FS", lag: 0 },
    { pred: "HV4010", succ: "HV3010", type: "FS", lag: 0 },
    { pred: "HV3010", succ: "HV3020", type: "SS", lag: 3 },
    { pred: "HV4010", succ: "HV3030", type: "FS", lag: 0 },
    { pred: "HV3030", succ: "HV3040", type: "SS", lag: 3 },
    { pred: "HV2040", succ: "HV3050", type: "SS", lag: 5 },
    { pred: "HV3050", succ: "HV3060", type: "FS", lag: 0 },
    { pred: "HV2040", succ: "HV3070", type: "SS", lag: 5 },
    { pred: "HV3020", succ: "HV3080", type: "FS", lag: 0 },
    { pred: "HV3040", succ: "HV3080", type: "FS", lag: 0 },
    { pred: "HV1090", succ: "HV4020", type: "FS", lag: 0 },
    { pred: "HV2030", succ: "HV4020", type: "FS", lag: 0 },
    { pred: "HV1130", succ: "HV4030", type: "FS", lag: 0 },
    { pred: "HV2040", succ: "HV4030", type: "SS", lag: 5 },
    { pred: "HV2060", succ: "HV4040", type: "FS", lag: 0 },
    { pred: "HV3080", succ: "HV4050", type: "FS", lag: 0 },
    { pred: "HV4050", succ: "HV4060", type: "SS", lag: 1 },
    { pred: "HV3060", succ: "HV4070", type: "FS", lag: 0 },
    { pred: "HV2080", succ: "HV5010", type: "FS", lag: 0 },
    { pred: "HV3080", succ: "HV5020", type: "FS", lag: 0 },
    { pred: "HV3080", succ: "HV5030", type: "FS", lag: 0 },
    { pred: "HV4010", succ: "HV5040", type: "FS", lag: 0 },
    { pred: "HV1070", succ: "HV6010", type: "FS", lag: 0 },
    { pred: "HV4030", succ: "HV6010", type: "FS", lag: 0 },
    { pred: "HV6010", succ: "HV6020", type: "FS", lag: 0 },
    { pred: "HV6020", succ: "HV6030", type: "SS", lag: 3 },
    { pred: "HV6030", succ: "HV6040", type: "FS", lag: 0 },
    { pred: "HV6040", succ: "HV6050", type: "FS", lag: 0 },
    { pred: "HV5010", succ: "HV7010", type: "FS", lag: 0 },
    { pred: "HV7010", succ: "HV7020", type: "SS", lag: 2 },
    { pred: "HV5010", succ: "HV7030", type: "FS", lag: 0 },
    { pred: "HV7030", succ: "HV7040", type: "FS", lag: 0 },
    { pred: "HV4020", succ: "HV8010", type: "FS", lag: 0 },
    { pred: "HV6050", succ: "HV8010", type: "FS", lag: 0 },
    { pred: "HV4010", succ: "HV8020", type: "FS", lag: 0 },
    { pred: "HV6050", succ: "HV8020", type: "FS", lag: 0 },
    { pred: "HV8010", succ: "HV8030", type: "FS", lag: 0 },
    { pred: "HV8020", succ: "HV8040", type: "FS", lag: 0 },
    { pred: "HV2070", succ: "HV8050", type: "FS", lag: 0 },
    { pred: "HV8030", succ: "HV8050", type: "FS", lag: 0 },
    { pred: "HV8030", succ: "HV8060", type: "FS", lag: 0 },
    { pred: "HV8040", succ: "HV8060", type: "FS", lag: 0 },
    { pred: "HV8050", succ: "HV8070", type: "FS", lag: 0 },
    { pred: "HV8060", succ: "HV8070", type: "FS", lag: 0 },
    { pred: "HV8070", succ: "HV8080", type: "FS", lag: 0 },
    { pred: "HV8080", succ: "HV8090", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Ductwork", "Piping", "Equipment", "Insulation", "Controls", "Trim", "TAB", "Commissioning", "Closeout"] },
    { name: "System", values: ["Supply Air", "Return Air", "Exhaust", "Chilled Water", "Hot Water", "Refrigerant", "Condensate", "Controls/BAS", "VRF"] },
  ],
};

// ═══════════════════════════════════════════════════════════════════════════════
// CIVIL / SITEWORK (TRADE-SPECIFIC) — $500K–$2M Site Development Package
// 10–16 week schedule, 55+ activities
// ═══════════════════════════════════════════════════════════════════════════════

export const civilTemplate: ScheduleTemplate = {
  name: "Civil / Sitework (Trade-Specific)",
  description: "Civil/sitework contractor schedule for commercial site development ($500K–$2M) — earthwork, utilities, paving, concrete, and site restoration",
  wbsNodes: [
    { code: "1.0", name: "Pre-Construction & Mobilization", parentCode: null, sortOrder: 10, color: "#f59e0b", textColor: "#ffffff" },
    { code: "2.0", name: "Erosion Control & Clearing", parentCode: null, sortOrder: 20, color: "#84cc16", textColor: "#ffffff" },
    { code: "3.0", name: "Earthwork", parentCode: null, sortOrder: 30, color: "#8b5cf6", textColor: "#ffffff" },
    { code: "3.1", name: "Mass Grading", parentCode: "3.0", sortOrder: 31, color: "#a78bfa", textColor: "#000000" },
    { code: "3.2", name: "Fine Grading", parentCode: "3.0", sortOrder: 32, color: "#c4b5fd", textColor: "#000000" },
    { code: "4.0", name: "Underground Utilities", parentCode: null, sortOrder: 40, color: "#3b82f6", textColor: "#ffffff" },
    { code: "4.1", name: "Storm Drainage", parentCode: "4.0", sortOrder: 41, color: "#60a5fa", textColor: "#000000" },
    { code: "4.2", name: "Sanitary Sewer", parentCode: "4.0", sortOrder: 42, color: "#93c5fd", textColor: "#000000" },
    { code: "4.3", name: "Water Main", parentCode: "4.0", sortOrder: 43, color: "#bfdbfe", textColor: "#000000" },
    { code: "4.4", name: "Dry Utilities", parentCode: "4.0", sortOrder: 44, color: "#dbeafe", textColor: "#000000" },
    { code: "5.0", name: "Stormwater Management", parentCode: null, sortOrder: 50, color: "#06b6d4", textColor: "#ffffff" },
    { code: "6.0", name: "Paving & Concrete", parentCode: null, sortOrder: 60, color: "#10b981", textColor: "#ffffff" },
    { code: "6.1", name: "Subbase & Aggregate", parentCode: "6.0", sortOrder: 61, color: "#34d399", textColor: "#000000" },
    { code: "6.2", name: "Asphalt Paving", parentCode: "6.0", sortOrder: 62, color: "#6ee7b7", textColor: "#000000" },
    { code: "6.3", name: "Concrete Flatwork", parentCode: "6.0", sortOrder: 63, color: "#a7f3d0", textColor: "#000000" },
    { code: "7.0", name: "Site Improvements", parentCode: null, sortOrder: 70, color: "#14b8a6", textColor: "#ffffff" },
    { code: "8.0", name: "Landscaping & Restoration", parentCode: null, sortOrder: 80, color: "#22c55e", textColor: "#ffffff" },
    { code: "9.0", name: "Closeout & Acceptance", parentCode: null, sortOrder: 90, color: "#ec4899", textColor: "#ffffff" },
  ],
  activities: [
    // 1.0 Pre-Con
    { activityId: "CV1010", name: "Pre-Construction Meeting & Survey", duration: 2, wbs: "1.0" },
    { activityId: "CV1020", name: "Submit Grading & Utility Permits", duration: 3, wbs: "1.0" },
    { activityId: "CV1030", name: "Permit Review & Approval", duration: 14, wbs: "1.0" },
    { activityId: "CV1040", name: "Utility Locates (811 / One-Call)", duration: 3, wbs: "1.0" },
    { activityId: "CV1050", name: "Mobilize Equipment & Trailer", duration: 2, wbs: "1.0" },
    // 2.0 Erosion Control
    { activityId: "CV2010", name: "Install Silt Fence & Inlet Protection", duration: 3, wbs: "2.0" },
    { activityId: "CV2020", name: "Install Construction Entrance", duration: 2, wbs: "2.0" },
    { activityId: "CV2030", name: "Tree Protection Fencing", duration: 2, wbs: "2.0" },
    { activityId: "CV2040", name: "Site Clearing & Grubbing", duration: 5, wbs: "2.0" },
    { activityId: "CV2050", name: "Strip & Stockpile Topsoil", duration: 3, wbs: "2.0" },
    // 3.0 Earthwork
    { activityId: "CV3010", name: "Mass Excavation — Cut Areas", duration: 10, wbs: "3.1" },
    { activityId: "CV3020", name: "Mass Fill — Embankment Areas", duration: 8, wbs: "3.1" },
    { activityId: "CV3030", name: "Proof Roll & Compaction Testing", duration: 3, wbs: "3.1" },
    { activityId: "CV3040", name: "Building Pad Preparation", duration: 5, wbs: "3.1" },
    { activityId: "CV3050", name: "Detention/Retention Pond Excavation", duration: 7, wbs: "3.1" },
    { activityId: "CV3060", name: "Fine Grading — Parking Areas", duration: 5, wbs: "3.2" },
    { activityId: "CV3070", name: "Fine Grading — Landscape Areas", duration: 3, wbs: "3.2" },
    { activityId: "CV3080", name: "Fine Grading — Building Perimeter", duration: 3, wbs: "3.2" },
    // 4.0 Underground Utilities
    { activityId: "CV4010", name: "Storm Drain — Main Trunk Line", duration: 10, wbs: "4.1" },
    { activityId: "CV4020", name: "Storm Drain — Laterals & Catch Basins", duration: 7, wbs: "4.1" },
    { activityId: "CV4030", name: "Storm Drain — Headwalls & Outfall", duration: 4, wbs: "4.1" },
    { activityId: "CV4040", name: "Sanitary Sewer — Main Line", duration: 7, wbs: "4.2" },
    { activityId: "CV4050", name: "Sanitary Sewer — Laterals & Manholes", duration: 5, wbs: "4.2" },
    { activityId: "CV4060", name: "Sanitary Sewer — Testing (air/mandrel)", duration: 3, wbs: "4.2" },
    { activityId: "CV4070", name: "Water Main — Pipe & Fittings", duration: 7, wbs: "4.3" },
    { activityId: "CV4080", name: "Water Main — Valves & Hydrants", duration: 4, wbs: "4.3" },
    { activityId: "CV4090", name: "Water Main — Pressure Test & Chlorination", duration: 3, wbs: "4.3" },
    { activityId: "CV4100", name: "Water Service — Building Connection", duration: 3, wbs: "4.3" },
    { activityId: "CV4110", name: "Electrical Ductbank & Conduit", duration: 5, wbs: "4.4" },
    { activityId: "CV4120", name: "Telecom/Fiber Conduit", duration: 4, wbs: "4.4" },
    { activityId: "CV4130", name: "Gas Main Extension (if applicable)", duration: 5, wbs: "4.4" },
    // 5.0 Stormwater
    { activityId: "CV5010", name: "Detention Pond — Liner & Rip-Rap", duration: 5, wbs: "5.0" },
    { activityId: "CV5020", name: "Bioretention / Rain Garden Construction", duration: 5, wbs: "5.0" },
    { activityId: "CV5030", name: "Underground Detention System (if applicable)", duration: 7, wbs: "5.0" },
    { activityId: "CV5040", name: "Stormwater Inspection & Certification", duration: 2, wbs: "5.0" },
    // 6.0 Paving & Concrete
    { activityId: "CV6010", name: "Aggregate Base — Parking Lot", duration: 5, wbs: "6.1" },
    { activityId: "CV6020", name: "Aggregate Base — Drive Aisles & Roads", duration: 4, wbs: "6.1" },
    { activityId: "CV6030", name: "Proof Roll & Compaction — Subbase", duration: 2, wbs: "6.1" },
    { activityId: "CV6040", name: "Asphalt — Binder Course", duration: 4, wbs: "6.2" },
    { activityId: "CV6050", name: "Asphalt — Surface Course", duration: 4, wbs: "6.2" },
    { activityId: "CV6060", name: "Striping & Pavement Markings", duration: 3, wbs: "6.2" },
    { activityId: "CV6070", name: "Concrete Curb & Gutter", duration: 7, wbs: "6.3" },
    { activityId: "CV6080", name: "Concrete Sidewalks", duration: 5, wbs: "6.3" },
    { activityId: "CV6090", name: "ADA Ramps & Detectable Warning", duration: 3, wbs: "6.3" },
    { activityId: "CV6100", name: "Concrete Dumpster Pads", duration: 2, wbs: "6.3" },
    // 7.0 Site Improvements
    { activityId: "CV7010", name: "Fencing & Gates", duration: 5, wbs: "7.0" },
    { activityId: "CV7020", name: "Retaining Walls", duration: 7, wbs: "7.0" },
    { activityId: "CV7030", name: "Site Lighting — Poles & Bases", duration: 5, wbs: "7.0" },
    { activityId: "CV7040", name: "Signage — Regulatory & Wayfinding", duration: 3, wbs: "7.0" },
    { activityId: "CV7050", name: "Bollards & Wheel Stops", duration: 2, wbs: "7.0" },
    // 8.0 Landscaping
    { activityId: "CV8010", name: "Irrigation System Installation", duration: 7, wbs: "8.0" },
    { activityId: "CV8020", name: "Spread Topsoil & Soil Amendments", duration: 4, wbs: "8.0" },
    { activityId: "CV8030", name: "Tree & Shrub Planting", duration: 5, wbs: "8.0" },
    { activityId: "CV8040", name: "Sod / Hydroseed", duration: 4, wbs: "8.0" },
    { activityId: "CV8050", name: "Mulch & Bed Edging", duration: 3, wbs: "8.0" },
    { activityId: "CV8060", name: "Remove Erosion Control (after stabilization)", duration: 2, wbs: "8.0" },
    // 9.0 Closeout
    { activityId: "CV9010", name: "As-Built Survey", duration: 3, wbs: "9.0" },
    { activityId: "CV9020", name: "Final Inspection — Municipality", duration: 3, wbs: "9.0" },
    { activityId: "CV9030", name: "Punch List & Corrections", duration: 5, wbs: "9.0" },
    { activityId: "CV9040", name: "SWPPP Closeout & NOT Filing", duration: 2, wbs: "9.0" },
    { activityId: "CV9050", name: "Demobilize Equipment", duration: 2, wbs: "9.0" },
    { activityId: "CV9060", name: "Substantial Completion", duration: 0, wbs: "9.0", activityType: "milestone" },
  ],
  relationships: [
    { pred: "CV1010", succ: "CV1020", type: "FS", lag: 0 },
    { pred: "CV1020", succ: "CV1030", type: "FS", lag: 0 },
    { pred: "CV1010", succ: "CV1040", type: "FS", lag: 0 },
    { pred: "CV1030", succ: "CV1050", type: "FS", lag: 0 },
    { pred: "CV1050", succ: "CV2010", type: "FS", lag: 0 },
    { pred: "CV2010", succ: "CV2020", type: "SS", lag: 0 },
    { pred: "CV2010", succ: "CV2030", type: "SS", lag: 0 },
    { pred: "CV2020", succ: "CV2040", type: "FS", lag: 0 },
    { pred: "CV2030", succ: "CV2040", type: "FS", lag: 0 },
    { pred: "CV2040", succ: "CV2050", type: "FS", lag: 0 },
    { pred: "CV2050", succ: "CV3010", type: "FS", lag: 0 },
    { pred: "CV3010", succ: "CV3020", type: "SS", lag: 5 },
    { pred: "CV3020", succ: "CV3030", type: "FS", lag: 0 },
    { pred: "CV3030", succ: "CV3040", type: "FS", lag: 0 },
    { pred: "CV3010", succ: "CV3050", type: "SS", lag: 5 },
    { pred: "CV3030", succ: "CV3060", type: "FS", lag: 0 },
    { pred: "CV3060", succ: "CV3070", type: "SS", lag: 2 },
    { pred: "CV3060", succ: "CV3080", type: "SS", lag: 2 },
    { pred: "CV3010", succ: "CV4010", type: "SS", lag: 5 },
    { pred: "CV4010", succ: "CV4020", type: "SS", lag: 5 },
    { pred: "CV4020", succ: "CV4030", type: "FS", lag: 0 },
    { pred: "CV3010", succ: "CV4040", type: "SS", lag: 5 },
    { pred: "CV4040", succ: "CV4050", type: "SS", lag: 3 },
    { pred: "CV4050", succ: "CV4060", type: "FS", lag: 0 },
    { pred: "CV3010", succ: "CV4070", type: "SS", lag: 5 },
    { pred: "CV4070", succ: "CV4080", type: "SS", lag: 3 },
    { pred: "CV4080", succ: "CV4090", type: "FS", lag: 0 },
    { pred: "CV4090", succ: "CV4100", type: "FS", lag: 0 },
    { pred: "CV4010", succ: "CV4110", type: "SS", lag: 5 },
    { pred: "CV4110", succ: "CV4120", type: "SS", lag: 2 },
    { pred: "CV4070", succ: "CV4130", type: "SS", lag: 3 },
    { pred: "CV3050", succ: "CV5010", type: "FS", lag: 0 },
    { pred: "CV5010", succ: "CV5020", type: "FS", lag: 0 },
    { pred: "CV4010", succ: "CV5030", type: "FS", lag: 0 },
    { pred: "CV5020", succ: "CV5040", type: "FS", lag: 0 },
    { pred: "CV5030", succ: "CV5040", type: "FS", lag: 0 },
    { pred: "CV3060", succ: "CV6010", type: "FS", lag: 0 },
    { pred: "CV4060", succ: "CV6010", type: "FS", lag: 0 },
    { pred: "CV4090", succ: "CV6010", type: "FS", lag: 0 },
    { pred: "CV6010", succ: "CV6020", type: "SS", lag: 2 },
    { pred: "CV6020", succ: "CV6030", type: "FS", lag: 0 },
    { pred: "CV6030", succ: "CV6040", type: "FS", lag: 0 },
    { pred: "CV6040", succ: "CV6050", type: "FS", lag: 0 },
    { pred: "CV6050", succ: "CV6060", type: "FS", lag: 2 },
    { pred: "CV3060", succ: "CV6070", type: "FS", lag: 0 },
    { pred: "CV6070", succ: "CV6080", type: "SS", lag: 3 },
    { pred: "CV6080", succ: "CV6090", type: "SS", lag: 2 },
    { pred: "CV6070", succ: "CV6100", type: "SS", lag: 3 },
    { pred: "CV6070", succ: "CV7010", type: "FS", lag: 0 },
    { pred: "CV3080", succ: "CV7020", type: "FS", lag: 0 },
    { pred: "CV6050", succ: "CV7030", type: "FS", lag: 0 },
    { pred: "CV4110", succ: "CV7030", type: "FS", lag: 0 },
    { pred: "CV6060", succ: "CV7040", type: "FS", lag: 0 },
    { pred: "CV6060", succ: "CV7050", type: "FS", lag: 0 },
    { pred: "CV3070", succ: "CV8010", type: "FS", lag: 0 },
    { pred: "CV8010", succ: "CV8020", type: "FS", lag: 0 },
    { pred: "CV8020", succ: "CV8030", type: "FS", lag: 0 },
    { pred: "CV8030", succ: "CV8040", type: "SS", lag: 2 },
    { pred: "CV8040", succ: "CV8050", type: "FS", lag: 0 },
    { pred: "CV8050", succ: "CV8060", type: "FS", lag: 30 },
    { pred: "CV7050", succ: "CV9010", type: "FS", lag: 0 },
    { pred: "CV8050", succ: "CV9010", type: "FS", lag: 0 },
    { pred: "CV9010", succ: "CV9020", type: "FS", lag: 0 },
    { pred: "CV9020", succ: "CV9030", type: "FS", lag: 0 },
    { pred: "CV8060", succ: "CV9040", type: "FS", lag: 0 },
    { pred: "CV9030", succ: "CV9050", type: "FS", lag: 0 },
    { pred: "CV9040", succ: "CV9060", type: "FS", lag: 0 },
    { pred: "CV9050", succ: "CV9060", type: "FS", lag: 0 },
  ],
  codeCategories: [
    { name: "Phase", values: ["Pre-Con", "Erosion Control", "Earthwork", "Utilities", "Stormwater", "Paving", "Concrete", "Site Improvements", "Landscaping", "Closeout"] },
    { name: "System", values: ["Storm Drain", "Sanitary Sewer", "Water Main", "Electrical", "Telecom", "Gas", "Paving", "Concrete", "Landscape", "Erosion Control"] },
  ],
};
